ness2::herm_matrix_ness
fft_array ness2::herm_matrix_ness::les_
Lesser component.
Referenced by get_les, ness2::green_equilibrium_ness_bose, ness2::green_equilibrium_ness_fermi, left_multiply, left_multiply_hermconj, lesser, lesser, right_multiply, right_multiply_hermconj, set_les.
int ness2::herm_matrix_ness::Nft_
FFT length.
Referenced by ness2::cntr2ness, ness2::cntr2ness, ness2::cntr2ness, ness2::green_equilibrium_ness_bose, ness2::green_equilibrium_ness_fermi, ness2::green_equilibrium_ret_ness_adaptive, ness2::ness2cntr, ness2::ness2cntr, ness2::ness2cntr, read_from_cntr.
fft_array ness2::herm_matrix_ness::ret_
Retarded component.
Referenced by get_ret, ness2::green_equilibrium_ness_bose, ness2::green_equilibrium_ness_fermi, left_multiply, left_multiply_hermconj, retarded, retarded, right_multiply, right_multiply_hermconj, set_ret.
int ness2::herm_matrix_ness::size1_
logical matrix size
Referenced by ness2::cntr2ness, ness2::cntr2ness, ness2::cntr2ness, ness2::green_equilibrium_ness_bose, ness2::green_equilibrium_ness_fermi, ness2::ness2cntr, ness2::ness2cntr, ness2::ness2cntr, read_from_cntr.
void ness2::herm_matrix_ness::fft_to_freq()
Transform both components to the frequency domain.
void ness2::herm_matrix_ness::fft_to_time()
Transform both components back to the time domain.
void ness2::herm_matrix_ness::force_equilibrium(int bosefermi, double beta, double mu, double h)
Enforce thermal equilibrium for the lesser Green's function.
Computes $ G^<(t) $ in thermal equilibrium for either bosons or fermions, using the fluctuation-dissipation relation and the retarded Green's function $ G^R(t) $. This method performs: Fourier transform of $ G^R(t) $ to $ G^R(\omega) $ using FFT with step size h (equivalent to integral_transform_to_freq with FFT_TRAPEZ), Constructs $ G^<(\omega) $ via: \[ G^<(\omega) = \mp 2i\, f(\omega - \mu)\, \mathrm{Im}\, G^R(\omega), \] where $ f(x) = 1 / (e^{\beta x} \pm 1) $ is the Bose-Einstein (+) or Fermi-Dirac (–) distribution, Inverse FFT to obtain $ G^<(t) $. bosefermi Sign indicator: +1 for bosons, -1 for fermions beta Inverse temperature $ \beta $ mu Chemical potential $ \mu $ h Time step size used in the FFT
void ness2::herm_matrix_ness::get_les(int t, MatrixType &M, fft_domain type) const
Get the lesser component of this herm_matrix_ness $ A $ at time index $ t $ (with periodic wrapping) and write to a matrix $ M $: $ M = A^<(t) $.
MatrixType Any Eigen-compatible complex matrix type. t Time/freq index (wrapped periodically). M Matrix to fill with values. type Whether to read from time or frequency array (fft_domain::time or fft_domain::freq).
References les_.
Referenced by ness2::ness2cntr, ness2::ness2cntr, ness2::ness2cntr.
void ness2::herm_matrix_ness::get_ret(int t, MatrixType &M, fft_domain type) const
Get the retarded component of this herm_matrix_ness $ A $ at time index $ t $ (with periodic wrapping) and write to a matrix $ M $: $ M = A^R(t) $.
MatrixType Any Eigen-compatible complex matrix type. t Time/freq index (wrapped periodically). M Matrix to fill with values. type Whether to read from time or frequency array (fft_domain::time or fft_domain::freq).
References ret_.
Referenced by ness2::ness2cntr, ness2::ness2cntr, ness2::ness2cntr.
ness2::herm_matrix_ness::herm_matrix_ness(const herm_matrix_ness &other)
Copy constructor.
References herm_matrix_ness.
ness2::herm_matrix_ness::herm_matrix_ness(int Nft=4, int size=1, unsigned FFTW_FLAG=FFTW_ESTIMATE)
Constructor.
Nft Length of arrays size Logical matrix size (size × size). FFTW_FLAG Planning flag for FFTW (default: FFTW_ESTIMATE).
Referenced by herm_matrix_ness, incr, operator=, set_matrixelement.
void ness2::herm_matrix_ness::incr(const herm_matrix_ness &B, cplx alpha, fft_domain type)
Increment this herm_matrix_ness $ A $ by another scaled herm_matrix_ness $ B $: $ A^{R,<} \to A^{R,<} + \alpha \cdot B^{R,<} $.
B Another herm_matrix_ness with matching dimensions. alpha Complex scaling factor. type Whether to operate on time or frequency arrays (fft_domain::time or fft_domain::freq).
References herm_matrix_ness.
void ness2::herm_matrix_ness::integral_transform_to_freq(double h, fft_integral_method method=FFT_TRAPEZ)
Compute the frequency-domain Fourier integral of the retarded Green's function.
This function computes the approximate Fourier integral \[G^R(\omega) = \int_0^{T} dt\, e^{i \omega t} G^R(t), \] and \[G^<(\omega) = \int_{-T}^{T} dt\, e^{i \omega t} G^<(t), \] where $ T = (N_{ft}/2- 1) \cdot h $, using either: a simple discrete approximation if method=FFT_TRAPEZ} (default), and a cubically corrected Fourier transform if method=FFT_CUBIC, based on Numerical Recipes (Press et al., Chapter 13.9). The integral is computed for all frequencies $ -(N_{ft}/2-1),\dots,(N_{ft}/2-1) $ , only the Nyqusit point $ N_{ft}/2 $ is set to zero. h timestep method Method for calculating the integral transform (FFT_TRAPEZ default)
References ness2::FFT_TRAPEZ.
void ness2::herm_matrix_ness::integral_transform_to_time(double h, fft_integral_method method=FFT_TRAPEZ)
Compute the time-domain Fourier integral of the retarded Green's function.
This function computes the approximate Fourier integral \[G^R(t) = -i\theta(t) \int_{-W}^{W} dw\, e^{-i \omega t} (-1/\pi)*ImG^R(w), \] and \[G^<(t) = \int_{-W}^{W} dw\, e^{-i \omega t} G^<(w)/(2\pi) \] where $ W = (N_{ft}/2 - 1) \cdot d\omega $, and $ d\omega=\pi/(N_{ft}/2 \cdot h) $ , and $ h $ is the timestep, using either: a simple discrete approximation if method=FFT_TRAPEZ (default), and a cubically corrected Fourier transform if method=FFT_CUBIC, based on Numerical Recipes (Press et al., Chapter 13.9). Only times $ 0,...,(N_{ft}/2-1) $ are set, all others are set to zero h timestep method Method for calculating the DFT (FFT_TRAPEZ default)
References ness2::FFT_TRAPEZ.
Referenced by ness2::green_equilibrium_ness_bose, ness2::green_equilibrium_ness_fermi.
void ness2::herm_matrix_ness::left_multiply(const MatrixType &M, fft_domain type)
Multiply each time/frequency matrix for both ret and les of this herm_matrix_ness $ A $ from the left by a complex matrix $ M $: $ A^{R,<}(t) \to M \cdot A^{R,<}(t) $.
MatrixType Any Eigen-compatible complex matrix type. M Matrix to left-multiply with. type Whether to apply to time or frequency domain data (fft_domain::time or fft_domain::freq).
References les_, ret_.
void ness2::herm_matrix_ness::left_multiply_hermconj(const MatrixType &M, fft_domain type)
Multiply each time/frequency matrix for both ret and les of this herm_matrix_ness $ A $ from the left by the hermitian conjugate of a complex matrix $ M $: $ A^{R,<}(t) \to M^\dagger \cdot A^{R,<}(t) $.
MatrixType Any Eigen-compatible complex matrix type. M Matrix to left-multiply with. type Whether to apply to time or frequency domain data (fft_domain::time or fft_domain::freq).
References les_, ret_.
fft_array & ness2::herm_matrix_ness::lesser()
Access the lesser component.
References les_.
const fft_array & ness2::herm_matrix_ness::lesser() const
Const access to the lesser component.
References les_.
herm_matrix_ness & ness2::herm_matrix_ness::operator=(const herm_matrix_ness &other)
Copy assignment operator.
References herm_matrix_ness.
void ness2::herm_matrix_ness::read_from_cntr(cntr::herm_matrix< T > &Gcntr, int tstp)
Import Green's function data from a cntr::herm_matrix at a specific time step.
This method initializes the retarded and lesser components of the Green's function from a cntr::herm_matrix<T> at a given time step tstp. It extracts values $ G^R(t_{\text{stp}}, t_{\text{stp}} - i) $ and $ G^<(t_{\text{stp}}, t_{\text{stp}} - i) $ for all $ i \leq \min(t_{\text{stp}}, N_{\text{ft}} / 2 - 1) $, and stores them in the time-domain representation of this ness2::herm_matrix_ness object. The lesser component is symmetrized to enforce Hermitian structure: $ G^<(-t) = -[G^<(t)]^\dagger $. T Scalar type of the input matrix (e.g., std::complex<double>). Gcntr The source Green's function in cntr::herm_matrix<T> format. tstp The reference time step (must satisfy $ {\tt tstp} \leq \tt Gcntr.nt() $). std::runtime_error If matrix dimensions mismatch or tstp is out of range.
References Nft_, cntr::herm_matrix< T >::nt, set_les, set_ret, set_zero, cntr::herm_matrix< T >::size1, size1_, ness2::time.
void ness2::herm_matrix_ness::read_from_hdf5(const char *filename, const char *groupname, unsigned FFTW_FLAG=FFTW_ESTIMATE)
Read Green's function data from a given hdf5 file and group.
Opens the desired hdf5 file, reads the ret_, les_, Nft and size data from the specified group into the herm_matrix_ness object and closes the file. filename Name of the hdf5 file. groupname Name of the top-level group. FFTW_FLAG FFTW planning flag to use if resizing (default: FFTW_ESTIMATE).
void ness2::herm_matrix_ness::read_from_hdf5(hid_t group_id, const char *groupname, unsigned FFTW_FLAG=FFTW_ESTIMATE)
Helper function: Read from a named subgroup under the given hdf5 group.
Opens the specified subgroup, reads the object, and closes the subgroup. group_id hdf5 parent group identifier. groupname Name of the subgroup to open. FFTW_FLAG FFTW planning flag to use if resizing (default: FFTW_ESTIMATE).
void ness2::herm_matrix_ness::read_from_hdf5(hid_t group_id, unsigned FFTW_FLAG=FFTW_ESTIMATE)
Helper function: Read the herm_matrix_ness data (ret and les components) from an hdf5 group.
If the stored dimensions differ from the current object, automatically resizes the object using the provided FFTW_FLAG. group_id hdf5 group identifier. FFTW_FLAG FFTW planning flag to use if resizing (default: FFTW_ESTIMATE).
fft_array & ness2::herm_matrix_ness::retarded()
Access the retarded component.
References ret_.
Referenced by ness2::green_equilibrium_ret_ness_adaptive.
const fft_array & ness2::herm_matrix_ness::retarded() const
Const access to the retarded component.
References ret_.
void ness2::herm_matrix_ness::right_multiply(const MatrixType &M, fft_domain type)
Multiply each time/frequency matrix for both ret and les of this herm_matrix_ness $ A $ from the right by a complex matrix $ M $: $ A^{R,<}(t) \to A^{R,<}(t) \cdot M $.
MatrixType Any Eigen-compatible complex matrix type. M Matrix to right-multiply with. type Whether to apply to time or frequency domain data (fft_domain::time or fft_domain::freq).
References les_, ret_.
void ness2::herm_matrix_ness::right_multiply_hermconj(const MatrixType &M, fft_domain type)
Multiply each time/frequency matrix for both ret and les of this herm_matrix_ness $ A $ from the right by the hermitian conjugate of a complex matrix $ M $: $ A^{R,<}(t) \to A^{R,<}(t) \cdot M^\dagger $.
MatrixType Any Eigen-compatible complex matrix type. M Matrix to left-multiply with. type Whether to apply to time or frequency domain data (fft_domain::time or fft_domain::freq).
References les_, ret_.
void ness2::herm_matrix_ness::set_les(int t, const MatrixType &M, fft_domain type)
Set the lesser component of this herm_matrix_ness $ A $ at time index $ t $ (with periodic wrapping) from a matrix $ M $: $ A^<(t) = M $.
MatrixType Any Eigen-compatible complex matrix type. t Time index (wrapped periodically). M Matrix to assign. type Whether to apply to time or frequency array (fft_domain::time or fft_domain::freq).
References les_.
Referenced by ness2::cntr2ness, ness2::cntr2ness, ness2::cntr2ness, ness2::green_equilibrium_ness_bose, ness2::green_equilibrium_ness_fermi, read_from_cntr.
void ness2::herm_matrix_ness::set_matrixelement(int i1, int i2, const herm_matrix_ness &B, int j1, int j2, fft_domain type)
Set one matrix element (both ret and les) of this herm_matrix_ness $ A $ from another herm_matrix_ness $ B $.
This sets $ A^{R,<}(i_1, i_2)(t) = B^{R,<}(j_1, j_2)(t) $ across all times or frequencies. i1 Row index in $ A(i_1, i_2) $. i2 Column index in $ A(i_1, i_2) $. B Source fft_array. j1 Row index in $ B(j_1, j_2) $. j2 Column index in $ B(j_1, j_2) $. type Whether to operate on time or frequency arrays (fft_domain::time or fft_domain::freq).
References herm_matrix_ness.
void ness2::herm_matrix_ness::set_ret(int t, const MatrixType &M, fft_domain type)
Set the retarded component of this herm_matrix_ness $ A $ at time index $ t $ (with periodic wrapping) from a matrix $ M $: $ A^R(t) = M $.
MatrixType Any Eigen-compatible complex matrix type. t Time/frequency index (wrapped periodically). M Matrix to assign. type Whether to apply to time or frequency array (fft_domain::time or fft_domain::freq).
References ret_.
Referenced by ness2::cntr2ness, ness2::cntr2ness, ness2::cntr2ness, ness2::green_equilibrium_ness_bose, ness2::green_equilibrium_ness_fermi, read_from_cntr.
void ness2::herm_matrix_ness::set_zero(fft_domain type)
Set all elements of both ret and les to zero.
type Whether to clear time or frequency arrays (fft_domain::time or fft_domain::freq).
Referenced by ness2::cntr2ness, ness2::cntr2ness, ness2::cntr2ness, read_from_cntr.
void ness2::herm_matrix_ness::smul(cplx alpha, fft_domain type)
Scale both ret and les of this herm_matrix_ness $ A $ in-place by a complex scalar: $ A^{R,<} \to \alpha \cdot A^{R,<} $.
alpha Complex scaling factor. type Whether to operate on time or frequency arrays (fft_domain::time or fft_domain::freq).
void ness2::herm_matrix_ness::write_to_hdf5(const char *filename, const char *groupname) const
Write Green's function to a hdf5 file under the given group name.
Opens or creates the hdf5 file if not exisitng, writes theret_, les_, Nft and size data of the herm_matrix_ness under the specified group name and closes the file. filename Name of the hdf5 file. groupname Name of the top-level group to create.
void ness2::herm_matrix_ness::write_to_hdf5(hid_t group_id) const
Print the Green's function (ret and les, time and frequency) to a text file.
Outputs: Header line: # Nft size1 `precision Blocks for ret_time, les_time, ret_freq, les_freq filename Path to the text file. precision Number of digits for real/imaginary part (default: 12). */ void print_to_file(const std::string& filename, int precision = 12) const; /** Read the Green's function data from a text file. Expects the same format as produced by print_to_file. Resizes internal arrays if needed using the provided FFTW_FLAG. filename Path to the text file. FFTW_FLAG FFTW planning flag to use if resizing (default: `FFTW_ESTIMATE). */ void read_from_file(const std::string& filename, unsigned FFTW_FLAG = FFTW_ESTIMATE); #if CNTR_USE_HDF5 == 1 /** Helper function: Write the herm_matrix_ness data (ret and les components) to an hdf5 group. Stores attributes for Nft_ and size1_ and delegates writing to the internal fft_array instances (ret_ and les_). group_id hdf5 group identifier.
void ness2::herm_matrix_ness::write_to_hdf5(hid_t group_id, const char *groupname) const
Helper function: Write to a named subgroup under the given hdf5 group.
Creates a subgroup named groupname, writes this object into it, and closes it. group_id hdf5 parent group identifier. groupname Name of the subgroup to create.
ness2::herm_matrix_ness::~herm_matrix_ness()
Destructor.