cntr::function_moving
typedef std::complex<T> cntr::function_moving< T >::cplx
cplx* cntr::function_moving< T >::data_
int cntr::function_moving< T >::element_size_
Size of the Matrix form; size1*size2.
int cntr::function_moving< T >::size1_
Number of the colums in the Matrix form.
int cntr::function_moving< T >::size2_
Number of the rows in the Matrix form.
int cntr::function_moving< T >::tc_
Cutoff time
cplx** cntr::function_moving< T >::value_
void cntr::function_moving< T >::clear(void)
int cntr::function_moving< T >::element_size(void) const
void cntr::function_moving< T >::forward(void)
cntr::function_moving< T >::function_moving()
Referenced by cntr::function_moving< T >::function_moving, cntr::function_moving< T >::operator=.
cntr::function_moving< T >::function_moving(const function_moving &g)
References cntr::function_moving< T >::function_moving.
cntr::function_moving< T >::function_moving(int tc, int size1=1)
References cntr::function_moving< T >::size1, cntr::function_moving< T >::tc.
void cntr::function_moving< T >::get_value(int i, EigenMatrix &M)
function_moving & cntr::function_moving< T >::operator=(const function_moving &g)
References cntr::function_moving< T >::function_moving.
cplx & cntr::function_moving< T >::operator[](int i)
References cntr::function_moving< T >::ptr.
cplx & cntr::function_moving< T >::operator[](int i) const
References cntr::function_moving< T >::ptr.
void cntr::function_moving< T >::print_to_file(const char *file, int precision=16)
cplx * cntr::function_moving< T >::ptr(int i)
Referenced by cntr::function_moving< T >::operator[], cntr::function_moving< T >::operator[].
void cntr::function_moving< T >::read_from_file(const char *file)
void cntr::function_moving< T >::resize(int tc, int size1)
References cntr::function_moving< T >::size1, cntr::function_moving< T >::tc.
void cntr::function_moving< T >::set_from_function_backward(function< T > &f, int tstp)
void cntr::function_moving< T >::set_from_function_backward(int tstp, function< T > &f)
void cntr::function_moving< T >::set_from_function_forward(int tstp, function< T > &f)
void cntr::function_moving< T >::set_value(int i, EigenMatrix &M)
int cntr::function_moving< T >::size1(void) const
Referenced by cntr::function_moving< T >::function_moving, cntr::function_moving< T >::resize.
int cntr::function_moving< T >::size2(void) const
int cntr::function_moving< T >::tc(void) const
Referenced by cntr::function_moving< T >::function_moving, cntr::function_moving< T >::resize.
cntr::function_moving< T >::~function_moving()