cntr::distributed_timestep_array_moving
distributed_array<std::complex<T> > cntr::distributed_timestep_array_moving< T >::data_
Pointer to the contiguous data
std::vector<cntr::herm_matrix_timestep_moving_view<T> > cntr::distributed_timestep_array_moving< T >::G_
Vector of views to the herm_matrix_timestep
int cntr::distributed_timestep_array_moving< T >::n_
Number of blocks
int cntr::distributed_timestep_array_moving< T >::ntasks_
MPI size if MPI is defined, else 1
int cntr::distributed_timestep_array_moving< T >::sig_
Fermion(boson)=-1(1)
int cntr::distributed_timestep_array_moving< T >::size_
Size of green's function
int cntr::distributed_timestep_array_moving< T >::t0_
Current timestep
int cntr::distributed_timestep_array_moving< T >::tc_
The maximum allowed timestep (set by size of data_)
int cntr::distributed_timestep_array_moving< T >::tid_
MPI rank if MPI is defined, else 0
void cntr::distributed_timestep_array_moving< T >::clear(void)
distributed_array< std::complex< T > > cntr::distributed_timestep_array_moving< T >::data(void) const
cntr::distributed_timestep_array_moving< T >::distributed_timestep_array_moving()
Referenced by cntr::distributed_timestep_array_moving< T >::distributed_timestep_array_moving, cntr::distributed_timestep_array_moving< T >::operator=.
cntr::distributed_timestep_array_moving< T >::distributed_timestep_array_moving(const distributed_timestep_array_moving &a)
References cntr::distributed_timestep_array_moving< T >::distributed_timestep_array_moving.
cntr::distributed_timestep_array_moving< T >::distributed_timestep_array_moving(int n, int tc, int t0, int size, int sig, bool mpi)
References cntr::distributed_timestep_array_moving< T >::n, cntr::distributed_timestep_array_moving< T >::sig, cntr::distributed_timestep_array_moving< T >::size, cntr::distributed_timestep_array_moving< T >::t0, cntr::distributed_timestep_array_moving< T >::tc.
cntr::herm_matrix_timestep_moving_view< T > & cntr::distributed_timestep_array_moving< T >::G(int j)
std::vector< cntr::herm_matrix_timestep_moving_view< T > > cntr::distributed_timestep_array_moving< T >::G(void) const
void cntr::distributed_timestep_array_moving< T >::mpi_bcast_all(void)
void cntr::distributed_timestep_array_moving< T >::mpi_bcast_block(int j)
int cntr::distributed_timestep_array_moving< T >::n(void) const
Referenced by cntr::distributed_timestep_array_moving< T >::distributed_timestep_array_moving.
int cntr::distributed_timestep_array_moving< T >::ntasks(void) const
distributed_timestep_array_moving< T > & cntr::distributed_timestep_array_moving< T >::operator=(const distributed_timestep_array_moving &a)
References cntr::distributed_timestep_array_moving< T >::distributed_timestep_array_moving.
void cntr::distributed_timestep_array_moving< T >::reset_tstp(int tstp)
void cntr::distributed_timestep_array_moving< T >::set_t0(int t0)
References cntr::distributed_timestep_array_moving< T >::t0.
int cntr::distributed_timestep_array_moving< T >::sig(void) const
Referenced by cntr::distributed_timestep_array_moving< T >::distributed_timestep_array_moving.
int cntr::distributed_timestep_array_moving< T >::size(void) const
Referenced by cntr::distributed_timestep_array_moving< T >::distributed_timestep_array_moving.
int cntr::distributed_timestep_array_moving< T >::t0(void) const
Referenced by cntr::distributed_timestep_array_moving< T >::distributed_timestep_array_moving, cntr::distributed_timestep_array_moving< T >::set_t0.
int cntr::distributed_timestep_array_moving< T >::tc(void) const
Referenced by cntr::distributed_timestep_array_moving< T >::distributed_timestep_array_moving.
int cntr::distributed_timestep_array_moving< T >::tid(void) const
cntr::distributed_timestep_array_moving< T >::~distributed_timestep_array_moving()