fourier::adft_func
typedef std::complex<double> fourier::adft_func::cplx
double* fourier::adft_func::a_
a[0..n-1], left endpoints
double* fourier::adft_func::b_
a[0..n-1], right endpoints
cplx* fourier::adft_func::data_
function data
cplx** fourier::adft_func::f_
int* fourier::adft_func::len_
len[0..n-1] number of data points in interval
int fourier::adft_func::n_
number of intervals
int fourier::adft_func::nmax_
size of data block
int fourier::adft_func::size_
size of data block
int fourier::adft_func::tot_
space currently used
fourier::adft_func::adft_func()
void fourier::adft_func::dft(double w, cplx &result, cplx &err)
Computes the cubically corrected DFT.
Purpose Computes the cubically corrected DFT by integrating over the individual intervals. w frequency $\omega$ in the Fourier integral result value of the Fourier integral err estimate of the error
References fourier::dft_cplx.
Referenced by ness2::compute_lesser, ness2::green_equilibrium_ret_ness_adaptive.
void fourier::adft_func::sample(double w, double a, double b, function &fz, int n, int limit)
Fourier samples the given function to determine the individual intervals.
Purpose Computes the Fourier integral for fixed frequency $\omega$. The interval $[a,b]$ is iteratively split until the error of the Fourier integral over each subinterval is smaller or equal than the smallest error. w frequency $\omega$ in the Fourier integral a lower interval bound b upper interval bound fz [template class function] scalar complex function n number of points in each interval limit max number of intervals
References fourier::dft_cplx.
Referenced by ness2::compute_lesser, ness2::green_equilibrium_ret_ness_adaptive.
fourier::adft_func::adft_func(const adft_func &a)
fourier::adft_func::adft_func(int size, int nmax)
Initializes the adft_func class
Purpose Initializes the adft_func class for a given number of points size and max. numer of intervals nmax. size number of points nmax max. numer of intervals
void fourier::adft_func::init(double a, double b, int n, function &fz)
Initializes the internal interval data and function values.
Purpose Initializes the internal interval data and function values on the internal grid. a lower interval bound b upper interval bound n number of points in [a,b] fz [template class function] scalar complex function
cplx * fourier::adft_func::interval_data(int i)
Returns the function values on the interval points.
Purpose Returns a pointer to the function values in the interval i. i index of interval
adft_func & fourier::adft_func::operator=(const adft_func &a)
void fourier::adft_func::resize(int size, int nmax)
Resizes the adft_func class.
Purpose Resizes the adft_func class for a given number of points size and max. numer of intervals nmax. size number of points nmax max. numer of intervals
void fourier::adft_func::split(int interv, function &fz)
Split interval interv by doubling points.
Purpose Split interval interv by doubling points. interv index of interval fz [template class function] scalar complex function
fourier::adft_func::~adft_func()