cntr::herm_matrix_moving
typedef std::complex<T> cntr::herm_matrix_moving< T >::cplx
typedef T cntr::herm_matrix_moving< T >::scalar_type
cplx* cntr::herm_matrix_moving< T >::data_
Pointer to the data array stoirng lesser and retarded component.
int cntr::herm_matrix_moving< T >::element_size_
Number of the rows in the Matrix form (currently: always size1=size2)</b> */ int size2_; /** \brief <b> Size of the Matrix form; size1*size2`.
cplx** cntr::herm_matrix_moving< T >::les_
Pointer to a pointer storing the lesser component.
cplx** cntr::herm_matrix_moving< T >::ret_
Pointer to a pointer storing the retarded component.
int cntr::herm_matrix_moving< T >::sig_
Bose = +1, Fermi =-1.
int cntr::herm_matrix_moving< T >::size1_
Number of the colums in the Matrix form.
int cntr::herm_matrix_moving< T >::tc_
Cutoff time.
void cntr::herm_matrix_moving< T >::clear(void)
void cntr::herm_matrix_moving< T >::clear_timestep(int delti)
cplx cntr::herm_matrix_moving< T >::density_matrix(int delti)
void cntr::herm_matrix_moving< T >::density_matrix(int i, Matrix &M)
int cntr::herm_matrix_moving< T >::element_size(void) const
void cntr::herm_matrix_moving< T >::forward(void)
void cntr::herm_matrix_moving< T >::get_gtr(int delti, int deltj, cplx &x)
void cntr::herm_matrix_moving< T >::get_gtr(int delti, int deltj, Matrix &M)
void cntr::herm_matrix_moving< T >::get_les(int delti, int deltj, cplx &x)
void cntr::herm_matrix_moving< T >::get_les(int delti, int deltj, Matrix &M)
void cntr::herm_matrix_moving< T >::get_ret(int delti, int deltj, cplx &x)
void cntr::herm_matrix_moving< T >::get_ret(int delti, int deltj, Matrix &M)
cntr::herm_matrix_moving< T >::herm_matrix_moving()
Referenced by cntr::herm_matrix_moving< T >::herm_matrix_moving, cntr::herm_matrix_moving< T >::incr_timestep, cntr::herm_matrix_moving< T >::operator=, cntr::herm_matrix_moving< T >::set_matrixelement, cntr::herm_matrix_moving< T >::set_timestep.
cntr::herm_matrix_moving< T >::herm_matrix_moving(const herm_matrix_moving &g)
References cntr::herm_matrix_moving< T >::herm_matrix_moving.
cntr::herm_matrix_moving< T >::herm_matrix_moving(int tc, int size1=1, int sig=-1)
References cntr::herm_matrix_moving< T >::sig, cntr::herm_matrix_moving< T >::size1, cntr::herm_matrix_moving< T >::tc.
void cntr::herm_matrix_moving< T >::incr_timestep(int delti, herm_matrix_moving< T > &g, int delti_g, cplx alpha=1.0)
References cntr::herm_matrix_moving< T >::herm_matrix_moving.
void cntr::herm_matrix_moving< T >::incr_timestep(int delti, herm_matrix_timestep_moving< T > &g, cplx alpha=1.0)
void cntr::herm_matrix_moving< T >::incr_timestep(int delti, herm_matrix_timestep_moving_view< T > &g, cplx alpha=1.0)
void cntr::herm_matrix_moving< T >::left_multiply(function_moving< T > &ft)
void cntr::herm_matrix_moving< T >::left_multiply_hermconj(function_moving< T > &ft)
cplx * cntr::herm_matrix_moving< T >::lesptr(int delti, int deltj)
herm_matrix_moving & cntr::herm_matrix_moving< T >::operator=(const herm_matrix_moving &g)
References cntr::herm_matrix_moving< T >::herm_matrix_moving.
void cntr::herm_matrix_moving< T >::print_to_file(const char *file, int precision=16)
void cntr::herm_matrix_moving< T >::read_from_file(const char *file)
void cntr::herm_matrix_moving< T >::read_from_hdf5(const char *filename, const char *groupname)
Reads data from an HDF5 file with a specified filename and group name.
void cntr::herm_matrix_moving< T >::read_from_hdf5(hid_t group_id)
Reads data from an HDF5 file for the specified group ID.
void cntr::herm_matrix_moving< T >::read_from_hdf5(hid_t group_id, const char *groupname)
Reads data from an HDF5 file for the specified group ID and groupname.
void cntr::herm_matrix_moving< T >::resize(int tc, int size1)
References cntr::herm_matrix_moving< T >::size1, cntr::herm_matrix_moving< T >::tc.
cplx * cntr::herm_matrix_moving< T >::retptr(int delti, int deltj)
void cntr::herm_matrix_moving< T >::right_multiply(function_moving< T > &ft)
void cntr::herm_matrix_moving< T >::right_multiply_hermconj(function_moving< T > &ft)
void cntr::herm_matrix_moving< T >::set_from_G_backward(const herm_pseudo< T > &g, int tstp_g)
Sets the data from a herm_matrix backward for the given timestep index tstp_g.
void cntr::herm_matrix_moving< T >::set_from_G_backward(herm_matrix< T > &g, herm_matrix< T > &gcc, int tstp_g)
void cntr::herm_matrix_moving< T >::set_from_G_backward(herm_matrix< T > &g, int tstp_g)
void cntr::herm_matrix_moving< T >::set_from_G_backward(int tstp_g, const herm_pseudo< T > &g)
Sets the data from a herm_matrix backward for the given timestep index tstp_g.
void cntr::herm_matrix_moving< T >::set_les(int delti, int deltj, cplx x)
void cntr::herm_matrix_moving< T >::set_les(int delti, int deltj, Matrix &M)
void cntr::herm_matrix_moving< T >::set_matrixelement(int delti, int i1, int i2, herm_matrix_moving< T > &g, int delti_g, int j1, int j2)
References cntr::herm_matrix_moving< T >::herm_matrix_moving.
void cntr::herm_matrix_moving< T >::set_matrixelement(int delti, int i1, int i2, herm_matrix_timestep_moving< T > &g, int j1, int j2)
void cntr::herm_matrix_moving< T >::set_matrixelement(int delti, int i1, int i2, herm_matrix_timestep_moving_view< T > &g, int j1, int j2)
void cntr::herm_matrix_moving< T >::set_ret(int delti, int deltj, cplx x)
void cntr::herm_matrix_moving< T >::set_ret(int delti, int deltj, Matrix &M)
void cntr::herm_matrix_moving< T >::set_timestep(int delti, herm_matrix< T > &g, herm_matrix< T > &gcc, int tstp_g)
void cntr::herm_matrix_moving< T >::set_timestep(int delti, herm_matrix_moving< T > &g, int delti_g)
References cntr::herm_matrix_moving< T >::herm_matrix_moving.
void cntr::herm_matrix_moving< T >::set_timestep(int delti, herm_matrix_timestep< T > &g, herm_matrix_timestep< T > &gcc)
void cntr::herm_matrix_moving< T >::set_timestep(int delti, herm_matrix_timestep_moving< T > &g)
void cntr::herm_matrix_moving< T >::set_timestep(int delti, herm_matrix_timestep_moving_view< T > &g)
void cntr::herm_matrix_moving< T >::set_timestep(int delti, herm_matrix_timestep_view< T > &g, herm_matrix_timestep_view< T > &gcc)
void cntr::herm_matrix_moving< T >::set_timestep_zero(int delti)
int cntr::herm_matrix_moving< T >::sig(void) const
Referenced by cntr::herm_matrix_moving< T >::herm_matrix_moving.
int cntr::herm_matrix_moving< T >::size1(void) const
Referenced by cntr::dyson_timestep, cntr::dyson_timestep, cntr::herm_matrix_moving< T >::herm_matrix_moving, cntr::herm_matrix_moving< T >::resize.
int cntr::herm_matrix_moving< T >::size2(void) const
void cntr::herm_matrix_moving< T >::smul(int delti, cplx alpha)
void cntr::herm_matrix_moving< T >::smul(int delti, T alpha)
int cntr::herm_matrix_moving< T >::tc(void) const
Referenced by cntr::herm_matrix_moving< T >::herm_matrix_moving, ness2::ness2cntr, cntr::herm_matrix_moving< T >::resize.
void cntr::herm_matrix_moving< T >::write_timestep_to_hdf5(int delti, const char *filename, const char *groupname, h5_mode mode=h5_mode::create_truncate)
Writes data to an HDF5 file with a specified filename and group name.
void cntr::herm_matrix_moving< T >::write_timestep_to_hdf5(int delti, hid_t group_id)
Writes data in timeslice delti to an HDF5 file for the specified group ID in the form a timeslice.
void cntr::herm_matrix_moving< T >::write_timestep_to_hdf5(int delti, hid_t group_id, const char *groupname)
void cntr::herm_matrix_moving< T >::write_to_hdf5(const char *filename, const char *groupname, h5_mode mode=h5_mode::create_truncate)
Writes data to an HDF5 file with a specified filename and group name.
void cntr::herm_matrix_moving< T >::write_to_hdf5(hid_t group_id)
Writes data to an HDF5 file for the specified group ID.
void cntr::herm_matrix_moving< T >::write_to_hdf5(hid_t group_id, const char *groupname)
Writes data to an HDF5 file for the specified group ID and creating a subgroup given a name.
cntr::herm_matrix_moving< T >::~herm_matrix_moving()