cntr::herm_matrix
typedef std::complex<T> cntr::herm_matrix< T >::cplx
typedef T cntr::herm_matrix< T >::scalar_type
int cntr::herm_matrix< T >::element_size_
Size of the Matrix form; size1*size2.
cplx* cntr::herm_matrix< T >::les_
Pointer to the lesser component. For $ t \leq t_1 $,'les_+ $((t_1 * (t_1 + 1)) / 2 + t) \; *$ element_size' corresponds to $(0,0)$-component of $ G^<(t,t_1) $
cplx* cntr::herm_matrix< T >::mat_
Pointer to the Matsubra component. 'mat_+ $ \tau \;*$ element_size' corresponds to $(0,0)$-component of $ G^M(\tau) $
int cntr::herm_matrix< T >::nt_
Maximum number of the time steps.
int cntr::herm_matrix< T >::ntau_
Number of the time grids on the Matsubara axis.
cplx* cntr::herm_matrix< T >::ret_
Pointer to the retarded component. For $ t \geq t_1 $,'ret_+ $((t * (t + 1)) / 2 + t_1) \;*$ element_size' corresponds to $(0,0)$-component of $ G^R(t,t_1) $
int cntr::herm_matrix< T >::sig_
Bose = +1, Fermi =-1.
int cntr::herm_matrix< T >::size1_
Number of the colums in the Matrix form.
int cntr::herm_matrix< T >::size2_
Number of the rows in the Matrix form.
cplx* cntr::herm_matrix< T >::tv_
Pointer to the left-mixing component. 'tv_+ $(t * (n_{\rm tau} + 1) + \tau) \;*$ element_size' corresponds to $(0,0)$-component of $ G^\rceil(t,\tau) $
void cntr::herm_matrix< T >::Bcast_timestep(int tstp, int root)
void cntr::herm_matrix< T >::clear(void)
void cntr::herm_matrix< T >::density_matrix(int tstp, Matrix &M) const
void cntr::herm_matrix< T >::get_timestep(int tstp, herm_matrix< T > &timestep) const
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::get_timestep(int tstp, herm_matrix_timestep< T > &timestep) const
cntr::herm_matrix< T >::herm_matrix()
Referenced by cntr::herm_matrix< T >::get_timestep, cntr::herm_matrix< T >::herm_matrix, cntr::herm_matrix< T >::herm_matrix, cntr::herm_matrix< T >::incr, cntr::herm_matrix< T >::incr, cntr::herm_matrix< T >::incr_timestep, cntr::herm_matrix< T >::incr_timestep, cntr::herm_matrix< T >::operator=, cntr::herm_matrix< T >::operator=, cntr::herm_matrix< T >::set_matrixelement, cntr::herm_matrix< T >::set_matrixelement, cntr::herm_matrix< T >::set_matrixelement, cntr::herm_matrix< T >::set_matrixelement, cntr::herm_matrix< T >::set_submatrix, cntr::herm_matrix< T >::set_submatrix, cntr::herm_matrix< T >::set_timestep.
cntr::herm_matrix< T >::herm_matrix(const herm_matrix &g)
References cntr::herm_matrix< T >::herm_matrix.
cntr::herm_matrix< T >::herm_matrix(herm_matrix &&g) noexcept
References cntr::herm_matrix< T >::herm_matrix.
cntr::herm_matrix< T >::herm_matrix(int nt, int ntau, int size1, int size2, int sig)
References cntr::herm_matrix< T >::nt, cntr::herm_matrix< T >::ntau, cntr::herm_matrix< T >::sig, cntr::herm_matrix< T >::size1, cntr::herm_matrix< T >::size2.
cntr::herm_matrix< T >::herm_matrix(int nt, int ntau, int size1=1, int sig=-1)
References cntr::herm_matrix< T >::nt, cntr::herm_matrix< T >::ntau, cntr::herm_matrix< T >::sig, cntr::herm_matrix< T >::size1.
void cntr::herm_matrix< T >::incr(herm_matrix< T > &g)
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::incr(herm_matrix< T > &g, cplx alpha)
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::incr_timestep(int tstp, herm_matrix< T > &g)
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::incr_timestep(int tstp, herm_matrix< T > &g, cplx alpha)
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::incr_timestep(int tstp, herm_matrix_timestep< T > &timestep)
void cntr::herm_matrix< T >::incr_timestep(int tstp, herm_matrix_timestep< T > &timestep, cplx alpha)
void cntr::herm_matrix< T >::left_multiply(int tstp, function< T > &ft, T weight=1.0)
void cntr::herm_matrix< T >::left_multiply_hermconj(int tstp, function< T > &ft, T weight=1.0)
int cntr::herm_matrix< T >::nt(void) const
Referenced by ness2::cntr2ness, cntr::dyson_timestep_omp, cntr::herm_matrix< T >::herm_matrix, cntr::herm_matrix< T >::herm_matrix, ness2::ness2cntr, ness2::herm_matrix_ness::read_from_cntr, cntr::herm_matrix< T >::resize, cntr::herm_matrix< T >::resize_discard, cntr::herm_matrix< T >::resize_nt.
int cntr::herm_matrix< T >::ntau(void) const
Referenced by cntr::dyson_timestep_omp, cntr::herm_matrix< T >::herm_matrix, cntr::herm_matrix< T >::herm_matrix, cntr::herm_matrix< T >::resize, cntr::herm_matrix< T >::resize_discard.
herm_matrix & cntr::herm_matrix< T >::operator=(const herm_matrix &g)
References cntr::herm_matrix< T >::herm_matrix.
herm_matrix & cntr::herm_matrix< T >::operator=(herm_matrix &&g) noexcept
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::print_to_file(const char *file, int precision=16) const
void cntr::herm_matrix< T >::read_from_file(const char *file)
void cntr::herm_matrix< T >::read_from_file(int nt1, const char *file)
void cntr::herm_matrix< T >::read_from_hdf5(const char *filename, const char *groupname)
void cntr::herm_matrix< T >::read_from_hdf5(hid_t group_id)
void cntr::herm_matrix< T >::read_from_hdf5(hid_t group_id, const char *groupname)
void cntr::herm_matrix< T >::read_from_hdf5(int nt1, const char *filename, const char *groupname)
void cntr::herm_matrix< T >::read_from_hdf5(int nt1, hid_t group_id)
void cntr::herm_matrix< T >::read_from_hdf5(int nt1, hid_t group_id, const char *groupname)
void cntr::herm_matrix< T >::Recv_timestep(int tstp, int root, int tag)
void cntr::herm_matrix< T >::Reduce_timestep(int tstp, int root)
void cntr::herm_matrix< T >::resize(int nt, int ntau, int size1)
References cntr::herm_matrix< T >::nt, cntr::herm_matrix< T >::ntau, cntr::herm_matrix< T >::size1.
void cntr::herm_matrix< T >::resize_discard(int nt, int ntau, int size1)
References cntr::herm_matrix< T >::nt, cntr::herm_matrix< T >::ntau, cntr::herm_matrix< T >::size1.
void cntr::herm_matrix< T >::resize_nt(int nt)
References cntr::herm_matrix< T >::nt.
void cntr::herm_matrix< T >::right_multiply(int tstp, function< T > &ft, T weight=1.0)
void cntr::herm_matrix< T >::right_multiply_hermconj(int tstp, function< T > &ft, T weight=1.0)
void cntr::herm_matrix< T >::Send_timestep(int tstp, int dest, int tag)
void cntr::herm_matrix< T >::set_matrixelement(int i1, int i2, herm_matrix< T > &g)
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::set_matrixelement(int i1, int i2, herm_matrix< T > &g, int j1, int j2)
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::set_matrixelement(int tstp, int i1, int i2, herm_matrix< T > &g)
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::set_matrixelement(int tstp, int i1, int i2, herm_matrix< T > &g, int j1, int j2)
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::set_matrixelement(int tstp, int i1, int i2, herm_matrix_timestep< T > &g, int j1, int j2)
void cntr::herm_matrix< T >::set_matrixelement(int tstp, int i1, int i2, herm_matrix_timestep< T > &timestep)
void cntr::herm_matrix< T >::set_sig(int sig)
References cntr::herm_matrix< T >::sig.
void cntr::herm_matrix< T >::set_submatrix(int tstp, std::vector< int > &i1, std::vector< int > &i2, herm_matrix< T > &g, std::vector< int > &j1, std::vector< int > &j2)
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::set_submatrix(std::vector< int > &i1, std::vector< int > &i2, herm_matrix< T > &g, std::vector< int > &j1, std::vector< int > &j2)
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::set_timestep(int tstp, herm_matrix &g1)
References cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::set_timestep(int tstp, herm_matrix_timestep< T > &timestep)
void cntr::herm_matrix< T >::set_timestep_zero(int tstp)
Referenced by ness2::ness2cntr.
int cntr::herm_matrix< T >::sig(void) const
Referenced by cntr::dyson_timestep_omp, cntr::herm_matrix< T >::herm_matrix, cntr::herm_matrix< T >::herm_matrix, cntr::herm_matrix< T >::set_sig.
int cntr::herm_matrix< T >::size1(void) const
Referenced by ness2::cntr2ness, cntr::dyson_timestep_omp, cntr::herm_matrix< T >::herm_matrix, cntr::herm_matrix< T >::herm_matrix, ness2::ness2cntr, ness2::herm_matrix_ness::read_from_cntr, cntr::herm_matrix< T >::resize, cntr::herm_matrix< T >::resize_discard.
int cntr::herm_matrix< T >::size2(void) const
Referenced by cntr::herm_matrix< T >::herm_matrix.
void cntr::herm_matrix< T >::smul(int tstp, cplx weight)
void cntr::herm_matrix< T >::smul(int tstp, T weight)
void cntr::herm_matrix< T >::write_to_hdf5(const char *filename, const char *groupname)
void cntr::herm_matrix< T >::write_to_hdf5(hid_t group_id)
void cntr::herm_matrix< T >::write_to_hdf5(hid_t group_id, const char *groupname)
void cntr::herm_matrix< T >::write_to_hdf5_slices(const char *filename, const char *groupname, int dt)
void cntr::herm_matrix< T >::write_to_hdf5_slices(hid_t group_id, const char *groupname, int dt)
void cntr::herm_matrix< T >::write_to_hdf5_slices(hid_t group_id, int dt)
void cntr::herm_matrix< T >::write_to_hdf5_tavtrel(const char *filename, const char *groupname, int dt)
void cntr::herm_matrix< T >::write_to_hdf5_tavtrel(hid_t group_id, const char *groupname, int dt)
void cntr::herm_matrix< T >::write_to_hdf5_tavtrel(hid_t group_id, int dt)
cntr::herm_matrix< T >::~herm_matrix()
cplx cntr::herm_matrix< T >::density_matrix(int i) const
int cntr::herm_matrix< T >::element_size(void) const
void cntr::herm_matrix< T >::get_gtr(int i, int j, cplx &x) const
void cntr::herm_matrix< T >::get_gtr(int i, int j, Matrix &M) const
void cntr::herm_matrix< T >::get_les(int i, int j, cplx &x) const
void cntr::herm_matrix< T >::get_les(int i, int j, Matrix &M) const
void cntr::herm_matrix< T >::get_mat(int i, cplx &x) const
void cntr::herm_matrix< T >::get_mat(int i, Matrix &M) const
void cntr::herm_matrix< T >::get_matminus(int i, cplx &x) const
void cntr::herm_matrix< T >::get_matminus(int i, Matrix &M) const
void cntr::herm_matrix< T >::get_ret(int i, int j, cplx &x) const
void cntr::herm_matrix< T >::get_ret(int i, int j, Matrix &M) const
void cntr::herm_matrix< T >::get_tv(int i, int j, cplx &x) const
void cntr::herm_matrix< T >::get_tv(int i, int j, Matrix &M) const
void cntr::herm_matrix< T >::get_vt(int i, int j, cplx &x) const
void cntr::herm_matrix< T >::get_vt(int i, int j, Matrix &M) const
void cntr::herm_matrix< T >::left_multiply(int tstp, cplx *f0, cplx *ft, T weight=1.0)
void cntr::herm_matrix< T >::left_multiply_(int tstp, function< T > &ft, T weight, std::integral_constant< int, SIZE >)
int cntr::herm_matrix< T >::les_offset(int t, int t1) const
cplx * cntr::herm_matrix< T >::lesptr(int i, int j)
const cplx * cntr::herm_matrix< T >::lesptr(int i, int j) const
int cntr::herm_matrix< T >::mat_offset(int tau) const
cplx * cntr::herm_matrix< T >::matptr(int i)
const cplx * cntr::herm_matrix< T >::matptr(int i) const
int cntr::herm_matrix< T >::ret_offset(int t, int t1) const
cplx * cntr::herm_matrix< T >::retptr(int i, int j)
const cplx * cntr::herm_matrix< T >::retptr(int i, int j) const
void cntr::herm_matrix< T >::right_multiply(int tstp, cplx *f0, cplx *ft, T weight=1.0)
void cntr::herm_matrix< T >::right_multiply_(int tstp, function< T > &ft, T weight, std::integral_constant< int, SIZE >)
void cntr::herm_matrix< T >::set_les(int i, int j, cplx x)
void cntr::herm_matrix< T >::set_les(int i, int j, Matrix &M)
void cntr::herm_matrix< T >::set_mat(int i, cplx x)
void cntr::herm_matrix< T >::set_mat(int i, Matrix &M)
void cntr::herm_matrix< T >::set_mat_herm(int i)
void cntr::herm_matrix< T >::set_mat_herm(void)
void cntr::herm_matrix< T >::set_mat_real(int i, Matrix &M)
void cntr::herm_matrix< T >::set_ret(int i, int j, cplx x)
void cntr::herm_matrix< T >::set_ret(int i, int j, Matrix &M)
void cntr::herm_matrix< T >::set_tv(int i, int j, cplx x)
void cntr::herm_matrix< T >::set_tv(int i, int j, Matrix &M)
int cntr::herm_matrix< T >::tv_offset(int t, int tau) const
cplx * cntr::herm_matrix< T >::tvptr(int i, int j)
const cplx * cntr::herm_matrix< T >::tvptr(int i, int j) const