ness::GF
double ness::GF::dgrid_
Grid spacing
int ness::GF::gf_type_
Green's function type, 0: time, 1: frequency
Referenced by gf_idx.
std::vector<Eigen::Map<Eigen::Matrix<cplx, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> > > ness::GF::Lesser
Save raw data pointer in a nice eigen3 structure
long ness::GF::ngrid_
Number of grid points
Referenced by gf_idx.
std::vector<Eigen::Map<Eigen::Matrix<cplx, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor> > > ness::GF::Retarded
Save raw data pointer in a nice eigen3 structure
int ness::GF::sign_
Sign +1 for bosons, -1 for fermions.
int ness::GF::size1_
Orbital dimension 1
int ness::GF::size2_
Orbital dimension 2
int ness::GF::data_size_
int ness::GF::el_size_
cplx * ness::GF::g_les
cplx* ness::GF::g_ret
Raw data pointers for Green's function
double* ness::GF::grid_
Raw data pointer for grid
int ness::GF::clear()
int ness::GF::get_element(int, int, const GF &, int, int)
References GF.
int ness::GF::get_element(int, int, GF &) const
References GF.
int ness::GF::get_submatrix(const std::vector< int > &, const std::vector< int > &, const GF &)
References GF.
ness::GF::GF()
Referenced by dyson, dyson_from_inv, get_element, get_element, get_submatrix, GF, GF, incr, operator+, operator=, set_element, set_element, set_submatrix.
ness::GF::GF(const GF &g)
References GF.
ness::GF::GF(double, int, int, int, int gf_type=freq_gf)
References ness::freq_gf.
ness::GF::GF(double, int, int, int, int, int gf_type)
ness::GF::GF(GF &&gf)
References GF.
int ness::GF::gf_idx(int w)
Return frequency, not stored in adcending order
References ness::freq_gf, gf_type_, ngrid_.
cdmatrix ness::GF::Greater(int) const
int ness::GF::incr(GF &gf, cplx weight=1.0)
References GF.
int ness::GF::left_multiply(const cdmatrix &mat)
GF ness::GF::operator+(const GF &g)
Operator + for Green's functions
References GF.
GF & ness::GF::operator=(const GF &g)
Operator = for Green's functions
References GF.
int ness::GF::reset_grid(double dgrid)
int ness::GF::right_multiply(const cdmatrix &mat)
int ness::GF::set_element(int, int, const GF &)
References GF.
int ness::GF::set_element(int, int, const GF &, int, int)
References GF.
void ness::GF::set_shiftGF(int shift)
int ness::GF::set_submatrix(const std::vector< int > &, const std::vector< int > &, const GF &)
References GF.
int ness::GF::smul(cplx weight=1.0)
ness::GF::~GF()
int dyson(GF &invg0, GF &self, GF &g)
References GF.
int dyson_from_inv(GF &g, GF &self)
References GF.
cplx * ness::GF::p_les(int w_idx, int i, int j) const
Return pointer to specific data in pointer for lesser component
cplx * ness::GF::p_ret(int w_idx, int i, int j) const
Return pointer to specific data in pointer for retarded component