cntr::herm_matrix_timestep_moving_view
typedef std::complex<T> cntr::herm_matrix_timestep_moving_view< T >::cplx
Complex number type.
typedef T cntr::herm_matrix_timestep_moving_view< T >::scalar_type
Scalar type.
int cntr::herm_matrix_timestep_moving_view< T >::element_size_
Total size of the matrix.
std::complex<T>* cntr::herm_matrix_timestep_moving_view< T >::les_
Pointer to lesser component.
std::complex<T>* cntr::herm_matrix_timestep_moving_view< T >::ret_
Pointer to retarded component.
int cntr::herm_matrix_timestep_moving_view< T >::sig_
Bose/Fermi statistical sign.
int cntr::herm_matrix_timestep_moving_view< T >::size1_
Number of columns.
int cntr::herm_matrix_timestep_moving_view< T >::size2_
Number of rows.
int cntr::herm_matrix_timestep_moving_view< T >::tc_
Time cut-off.
void cntr::herm_matrix_timestep_moving_view< T >::clear_timestep(void)
void cntr::herm_matrix_timestep_moving_view< T >::density_matrix(Matrix &M)
std::complex< T > cntr::herm_matrix_timestep_moving_view< T >::density_matrix(void)
int cntr::herm_matrix_timestep_moving_view< T >::element_size(void) const
void cntr::herm_matrix_timestep_moving_view< T >::get_gtr(int deltj, cplx &x)
void cntr::herm_matrix_timestep_moving_view< T >::get_gtr(int deltj, Matrix &M)
void cntr::herm_matrix_timestep_moving_view< T >::get_les(int deltj, cplx &x)
void cntr::herm_matrix_timestep_moving_view< T >::get_les(int deltj, Matrix &M)
Referenced by ness2::cntr2ness.
void cntr::herm_matrix_timestep_moving_view< T >::get_ret(int deltj, cplx &x)
void cntr::herm_matrix_timestep_moving_view< T >::get_ret(int deltj, Matrix &M)
Referenced by ness2::cntr2ness.
cntr::herm_matrix_timestep_moving_view< T >::herm_matrix_timestep_moving_view()
Referenced by cntr::herm_matrix_timestep_moving_view< T >::herm_matrix_timestep_moving_view, cntr::herm_matrix_timestep_moving_view< T >::incr_timestep, cntr::herm_matrix_timestep_moving_view< T >::operator=, cntr::herm_matrix_timestep_moving_view< T >::set_matrixelement, cntr::herm_matrix_timestep_moving_view< T >::set_timestep.
cntr::herm_matrix_timestep_moving_view< T >::herm_matrix_timestep_moving_view(const herm_matrix_timestep_moving_view &g)
References cntr::herm_matrix_timestep_moving_view< T >::herm_matrix_timestep_moving_view.
cntr::herm_matrix_timestep_moving_view< T >::herm_matrix_timestep_moving_view(herm_matrix_moving< T > &g)
cntr::herm_matrix_timestep_moving_view< T >::herm_matrix_timestep_moving_view(herm_matrix_moving< T > &g, int delt_g)
cntr::herm_matrix_timestep_moving_view< T >::herm_matrix_timestep_moving_view(herm_matrix_timestep_moving< T > &g)
void cntr::herm_matrix_timestep_moving_view< T >::incr_timestep(herm_matrix_moving< T > &g, int delt_g, cplx alpha)
void cntr::herm_matrix_timestep_moving_view< T >::incr_timestep(herm_matrix_timestep_moving< T > &g, cplx alpha)
void cntr::herm_matrix_timestep_moving_view< T >::incr_timestep(herm_matrix_timestep_moving_view< T > &g, cplx alpha)
References cntr::herm_matrix_timestep_moving_view< T >::herm_matrix_timestep_moving_view.
void cntr::herm_matrix_timestep_moving_view< T >::left_multiply(function_moving< T > &ft)
void cntr::herm_matrix_timestep_moving_view< T >::left_multiply_hermconj(function_moving< T > &ft)
std::complex< T > * cntr::herm_matrix_timestep_moving_view< T >::lesptr(int deltj)
Pointer to lesser component at a given time, representing G^<(t_lead,t_lead-deltj).
void cntr::herm_matrix_timestep_moving_view< T >::MPI_Reduce(int root)
Performs MPI reduction.
herm_matrix_timestep_moving_view & cntr::herm_matrix_timestep_moving_view< T >::operator=(const herm_matrix_timestep_moving_view &g)
References cntr::herm_matrix_timestep_moving_view< T >::herm_matrix_timestep_moving_view.
std::complex< T > * cntr::herm_matrix_timestep_moving_view< T >::retptr(int deltj)
Pointer to retarded component at a given time, representing G^R(t_lead,t_lead-deltj).
void cntr::herm_matrix_timestep_moving_view< T >::right_multiply(function_moving< T > &ft)
void cntr::herm_matrix_timestep_moving_view< T >::right_multiply_hermconj(function_moving< T > &ft)
void cntr::herm_matrix_timestep_moving_view< T >::set_les(int deltj, cplx x)
void cntr::herm_matrix_timestep_moving_view< T >::set_les(int deltj, Matrix &M)
Referenced by ness2::ness2cntr.
void cntr::herm_matrix_timestep_moving_view< T >::set_matrixelement(int i1, int i2, herm_matrix_moving< T > &G, int delt_g, int j1, int j2)
void cntr::herm_matrix_timestep_moving_view< T >::set_matrixelement(int i1, int i2, herm_matrix_timestep_moving< T > &G, int j1, int j2)
void cntr::herm_matrix_timestep_moving_view< T >::set_matrixelement(int i1, int i2, herm_matrix_timestep_moving_view< T > &G, int j1, int j2)
References cntr::herm_matrix_timestep_moving_view< T >::herm_matrix_timestep_moving_view.
void cntr::herm_matrix_timestep_moving_view< T >::set_ret(int deltj, cplx x)
void cntr::herm_matrix_timestep_moving_view< T >::set_ret(int deltj, Matrix &M)
Referenced by ness2::ness2cntr.
void cntr::herm_matrix_timestep_moving_view< T >::set_timestep(herm_matrix< T > &G, herm_matrix< T > &Gcc, int tstp_g)
void cntr::herm_matrix_timestep_moving_view< T >::set_timestep(herm_matrix_moving< T > &g1, int delt_g)
void cntr::herm_matrix_timestep_moving_view< T >::set_timestep(herm_matrix_timestep< T > &G, herm_matrix_timestep< T > &Gcc)
void cntr::herm_matrix_timestep_moving_view< T >::set_timestep(herm_matrix_timestep_moving< T > &g1)
void cntr::herm_matrix_timestep_moving_view< T >::set_timestep(herm_matrix_timestep_moving_view< T > &g1)
References cntr::herm_matrix_timestep_moving_view< T >::herm_matrix_timestep_moving_view.
void cntr::herm_matrix_timestep_moving_view< T >::set_timestep(herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
void cntr::herm_matrix_timestep_moving_view< T >::set_timestep_zero(void)
Referenced by ness2::ness2cntr.
int cntr::herm_matrix_timestep_moving_view< T >::sig(void) const
Returns the statistical sign (Bose = +1, Fermi = -1).
int cntr::herm_matrix_timestep_moving_view< T >::size1(void) const
Returns the number of columns.
Referenced by ness2::cntr2ness, ness2::ness2cntr.
int cntr::herm_matrix_timestep_moving_view< T >::size2(void) const
Returns the number of rows (CurrentlyL always the same as number of columns!).
void cntr::herm_matrix_timestep_moving_view< T >::smul(cplx alpha)
void cntr::herm_matrix_timestep_moving_view< T >::smul(T alpha)
int cntr::herm_matrix_timestep_moving_view< T >::tc(void) const
Returns the time cut-off.
Referenced by ness2::cntr2ness, ness2::ness2cntr.
void cntr::herm_matrix_timestep_moving_view< T >::write_to_hdf5(const char *filename, const char *groupname, h5_mode mode=h5_mode::create_truncate)
Writes data to an HDF5 file with a specified filename and group name.
void cntr::herm_matrix_timestep_moving_view< T >::write_to_hdf5(hid_t group_id)
Writes data to an HDF5 file for the specified group ID.
void cntr::herm_matrix_timestep_moving_view< T >::write_to_hdf5(hid_t group_id, const char *groupname)
Writes data to an HDF5 file for the specified group ID into a subgroup with specified name.
cntr::herm_matrix_timestep_moving_view< T >::~herm_matrix_timestep_moving_view()