cntr::herm_matrix_timestep
typedef std::complex<T> cntr::herm_matrix_timestep< T >::cplx
typedef T cntr::herm_matrix_timestep< T >::scalar_type
cplx* cntr::herm_matrix_timestep< T >::data_
Pointer to the data for the time step (tstp). 'data_+ $ t$ * element_size' correponds to (0,0)-component of $ G^R(tstp,t)$, 'data_+ $(tstp+1+\tau)$ * element_size' correponds to (0,0)-component of $ G^\rceil(tstp,\tau)$, 'data_+ $(tstp+1+n_{\tau}+1+t)$ * element_size' correponds to (0,0)-component of $ G^<(t,tstp)$.
int cntr::herm_matrix_timestep< T >::element_size_
Size of the Matrix form; size1*size2.
int cntr::herm_matrix_timestep< T >::ntau_
Number of the time grids on the Matsubara axis.
int cntr::herm_matrix_timestep< T >::sig_
Bose = +1, Fermi =-1.
int cntr::herm_matrix_timestep< T >::size1_
Number of the colums in the Matrix form.
int cntr::herm_matrix_timestep< T >::size2_
Number of the rows in the Matrix form.
int cntr::herm_matrix_timestep< T >::total_size_
Size of the data stored for the time step; $ (2*(tstp+1)+(n_{\tau}+1)) $ \;* element_size
int cntr::herm_matrix_timestep< T >::tstp_
time step.
void cntr::herm_matrix_timestep< T >::Bcast_timestep(int tstp, int root)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::clear(void)
void cntr::herm_matrix_timestep< T >::density_matrix(int tstp, cplx &rho)
References cntr::herm_matrix_timestep< T >::sig, cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::density_matrix(int tstp, Matrix &M)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::get_matrixelement(int i1, int i2, herm_matrix< T > &g)
cntr::herm_matrix_timestep< T >::herm_matrix_timestep()
Referenced by cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::incr, cntr::herm_matrix_timestep< T >::incr_timestep, cntr::herm_matrix_timestep< T >::operator=, cntr::herm_matrix_timestep< T >::operator=, cntr::herm_matrix_timestep< T >::set_matrixelement, cntr::herm_matrix_timestep< T >::set_matrixelement, cntr::herm_matrix_timestep< T >::set_submatrix, cntr::herm_matrix_timestep< T >::set_timestep.
cntr::herm_matrix_timestep< T >::herm_matrix_timestep(const herm_matrix_timestep &g)
References cntr::herm_matrix_timestep< T >::herm_matrix_timestep.
cntr::herm_matrix_timestep< T >::herm_matrix_timestep(herm_matrix_timestep &&g) noexcept
References cntr::herm_matrix_timestep< T >::herm_matrix_timestep.
cntr::herm_matrix_timestep< T >::herm_matrix_timestep(int tstp, int ntau, int size1, int sig)
References cntr::herm_matrix_timestep< T >::ntau, cntr::herm_matrix_timestep< T >::sig, cntr::herm_matrix_timestep< T >::size1, cntr::herm_matrix_timestep< T >::tstp.
cntr::herm_matrix_timestep< T >::herm_matrix_timestep(int tstp, int ntau, int size1, int size2, int sig)
References cntr::herm_matrix_timestep< T >::ntau, cntr::herm_matrix_timestep< T >::sig, cntr::herm_matrix_timestep< T >::size1, cntr::herm_matrix_timestep< T >::size2, cntr::herm_matrix_timestep< T >::tstp.
cntr::herm_matrix_timestep< T >::herm_matrix_timestep(int tstp, int ntau, int size1=1)
References cntr::herm_matrix_timestep< T >::ntau, cntr::herm_matrix_timestep< T >::size1, cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::incr(herm_matrix< T > &g, T weight=1.0)
void cntr::herm_matrix_timestep< T >::incr(herm_matrix_timestep< T > &g1, T weight)
References cntr::herm_matrix_timestep< T >::herm_matrix_timestep.
void cntr::herm_matrix_timestep< T >::incr_timestep(int tstp, herm_matrix< T > &g, T weight=1.0)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::incr_timestep(int tstp, herm_matrix_timestep< T > &g1, T weight)
References cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::left_multiply(function< T > &ft, T weight=1.0)
void cntr::herm_matrix_timestep< T >::left_multiply(int tstp, function< T > &ft, T weight=1.0)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::left_multiply_hermconj(int tstp, function< T > &ft, T weight=1.0)
References cntr::herm_matrix_timestep< T >::tstp.
cplx * cntr::herm_matrix_timestep< T >::lesptr(int i)
cplx * cntr::herm_matrix_timestep< T >::matptr(int i)
int cntr::herm_matrix_timestep< T >::ntau(void) const
Referenced by cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::Recv_timestep, cntr::herm_matrix_timestep< T >::resize.
herm_matrix_timestep & cntr::herm_matrix_timestep< T >::operator=(const herm_matrix_timestep &g)
References cntr::herm_matrix_timestep< T >::herm_matrix_timestep.
herm_matrix_timestep & cntr::herm_matrix_timestep< T >::operator=(herm_matrix_timestep &&g) noexcept
References cntr::herm_matrix_timestep< T >::herm_matrix_timestep.
void cntr::herm_matrix_timestep< T >::read_from_hdf5(const char *filename, const char *groupname)
void cntr::herm_matrix_timestep< T >::read_from_hdf5(hid_t group_id)
void cntr::herm_matrix_timestep< T >::read_from_hdf5(hid_t group_id, const char *groupname)
void cntr::herm_matrix_timestep< T >::Recv_timestep(int tstp, int root, int tag)
References cntr::herm_matrix_timestep< T >::ntau, cntr::herm_matrix_timestep< T >::size1, cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::Reduce_timestep(int tstp, int root)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::resize(int nt, int ntau, int size1)
References cntr::herm_matrix_timestep< T >::ntau, cntr::herm_matrix_timestep< T >::size1.
cplx * cntr::herm_matrix_timestep< T >::retptr(int i)
void cntr::herm_matrix_timestep< T >::right_multiply(function< T > &ft, T weight=1.0)
void cntr::herm_matrix_timestep< T >::right_multiply(int tstp, function< T > &ft, T weight=1.0)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::right_multiply_hermconj(int tstp, function< T > &ft, T weight=1.0)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::Send_timestep(int tstp, int dest, int tag)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::set_matrixelement(int i1, int i2, herm_matrix< T > &g, int j1, int j2)
void cntr::herm_matrix_timestep< T >::set_matrixelement(int i1, int i2, herm_matrix_timestep< T > &g, int j1, int j2)
References cntr::herm_matrix_timestep< T >::herm_matrix_timestep.
void cntr::herm_matrix_timestep< T >::set_matrixelement(int i1, int i2, herm_matrix_timestep_view< T > &g, int j1, int j2)
void cntr::herm_matrix_timestep< T >::set_matrixelement(int tstp, int i1, int i2, herm_matrix< T > &g, int j1, int j2)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::set_matrixelement(int tstp, int i1, int i2, herm_matrix_timestep< T > &g, int j1, int j2)
References cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::set_matrixelement(int tstp, int i1, int i2, herm_matrix_timestep_view< T > &g, int j1, int j2)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::set_submatrix(int tstp, std::vector< int > &i1, std::vector< int > &i2, herm_matrix< T > &g, std::vector< int > &j1, std::vector< int > &j2)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::set_submatrix(int tstp, std::vector< int > &i1, std::vector< int > &i2, herm_matrix_timestep< T > &g, std::vector< int > &j1, std::vector< int > &j2)
References cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::set_timestep(cyclic_timestep< T > &timestep, cyclic_timestep< T > &timestep_cc, int sig)
References cntr::herm_matrix_timestep< T >::sig.
void cntr::herm_matrix_timestep< T >::set_timestep(cyclic_timestep< T > &timestep, int sig)
References cntr::herm_matrix_timestep< T >::sig.
void cntr::herm_matrix_timestep< T >::set_timestep(int tstp, herm_matrix< T > &g1)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::set_timestep(int tstp, herm_matrix_timestep< T > &g1)
References cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::set_timestep_pseudo(cyclic_timestep< T > &timestep, cyclic_timestep< T > &timestep_cc, int sig)
References cntr::herm_matrix_timestep< T >::sig.
void cntr::herm_matrix_timestep< T >::set_timestep_pseudo(cyclic_timestep< T > &timestep, int sig)
References cntr::herm_matrix_timestep< T >::sig.
void cntr::herm_matrix_timestep< T >::set_timestep_zero(int tstp)
References cntr::herm_matrix_timestep< T >::tstp.
Referenced by ness2::ness2cntr.
int cntr::herm_matrix_timestep< T >::sig(void) const
Referenced by cntr::herm_matrix_timestep< T >::density_matrix, cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::set_timestep, cntr::herm_matrix_timestep< T >::set_timestep, cntr::herm_matrix_timestep< T >::set_timestep_pseudo, cntr::herm_matrix_timestep< T >::set_timestep_pseudo.
int cntr::herm_matrix_timestep< T >::size1(void) const
Referenced by ness2::cntr2ness, cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::herm_matrix_timestep, ness2::ness2cntr, cntr::herm_matrix_timestep< T >::Recv_timestep, cntr::herm_matrix_timestep< T >::resize.
int cntr::herm_matrix_timestep< T >::size2(void) const
Referenced by cntr::herm_matrix_timestep< T >::herm_matrix_timestep.
void cntr::herm_matrix_timestep< T >::smul(int tstp, T weight)
References cntr::herm_matrix_timestep< T >::tstp.
void cntr::herm_matrix_timestep< T >::smul(T weight)
int cntr::herm_matrix_timestep< T >::tstp(void) const
Referenced by cntr::herm_matrix_timestep< T >::Bcast_timestep, ness2::cntr2ness, cntr::herm_matrix_timestep< T >::density_matrix, cntr::herm_matrix_timestep< T >::density_matrix, cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::herm_matrix_timestep, cntr::herm_matrix_timestep< T >::incr_timestep, cntr::herm_matrix_timestep< T >::incr_timestep, cntr::herm_matrix_timestep< T >::left_multiply, cntr::herm_matrix_timestep< T >::left_multiply_hermconj, ness2::ness2cntr, cntr::herm_matrix_timestep< T >::Recv_timestep, cntr::herm_matrix_timestep< T >::Reduce_timestep, cntr::herm_matrix_timestep< T >::right_multiply, cntr::herm_matrix_timestep< T >::right_multiply_hermconj, cntr::herm_matrix_timestep< T >::Send_timestep, cntr::herm_matrix_timestep< T >::set_matrixelement, cntr::herm_matrix_timestep< T >::set_matrixelement, cntr::herm_matrix_timestep< T >::set_matrixelement, cntr::herm_matrix_timestep< T >::set_submatrix, cntr::herm_matrix_timestep< T >::set_submatrix, cntr::herm_matrix_timestep< T >::set_timestep, cntr::herm_matrix_timestep< T >::set_timestep, cntr::herm_matrix_timestep< T >::set_timestep_zero, cntr::herm_matrix_timestep< T >::smul.
cplx * cntr::herm_matrix_timestep< T >::tvptr(int i)
void cntr::herm_matrix_timestep< T >::write_to_hdf5(const char *filename, const char *groupname)
void cntr::herm_matrix_timestep< T >::write_to_hdf5(hid_t group_id)
void cntr::herm_matrix_timestep< T >::write_to_hdf5(hid_t group_id, const char *groupname)
cntr::herm_matrix_timestep< T >::~herm_matrix_timestep()
void cntr::herm_matrix_timestep< T >::Bcast_timestep(int tstp, int ntau, int size1, int root)
cplx cntr::herm_matrix_timestep< T >::density_matrix(int tstp)
void cntr::herm_matrix_timestep< T >::density_matrix(Matrix &M)
void cntr::herm_matrix_timestep< T >::get_gtr_t_tstp(int i, Matrix &M)
void cntr::herm_matrix_timestep< T >::get_gtr_tstp_t(int i, Matrix &M)
void cntr::herm_matrix_timestep< T >::get_les(int i, int j, cplx &x)
void cntr::herm_matrix_timestep< T >::get_les(int i, int j, Matrix &M)
void cntr::herm_matrix_timestep< T >::get_les_t_tstp(int i, Matrix &M)
get_les_t_tstp(int i,Matrix &M) M = Gles(i*h,tstp) etc.
void cntr::herm_matrix_timestep< T >::get_les_tstp_t(int i, Matrix &M)
void cntr::herm_matrix_timestep< T >::get_mat(int i, cplx &x)
void cntr::herm_matrix_timestep< T >::get_mat(int i, Matrix &M)
void cntr::herm_matrix_timestep< T >::get_matminus(int i, cplx &x)
void cntr::herm_matrix_timestep< T >::get_matminus(int i, Matrix &M)
void cntr::herm_matrix_timestep< T >::get_matminus(int i, Matrix &M, int sig)
void cntr::herm_matrix_timestep< T >::get_ret(int i, int j, cplx &x)
void cntr::herm_matrix_timestep< T >::get_ret(int i, int j, Matrix &M)
void cntr::herm_matrix_timestep< T >::get_ret_t_tstp(int i, Matrix &M)
void cntr::herm_matrix_timestep< T >::get_ret_tstp_t(int j, Matrix &M)
void cntr::herm_matrix_timestep< T >::get_tv(int i, int j, cplx &x)
void cntr::herm_matrix_timestep< T >::get_tv(int i, int j, Matrix &M)
void cntr::herm_matrix_timestep< T >::get_tv(int j, Matrix &M)
void cntr::herm_matrix_timestep< T >::get_vt(int i, int j, cplx &x)
void cntr::herm_matrix_timestep< T >::get_vt(int i, Matrix &M, int sig)
void cntr::herm_matrix_timestep< T >::left_multiply(cplx *f0, cplx *ft, T weight=1.0)
void cntr::herm_matrix_timestep< T >::Recv_timestep(int tstp, int ntau, int size1, int root, int tag)
void cntr::herm_matrix_timestep< T >::Reduce_timestep(int root)
void cntr::herm_matrix_timestep< T >::right_multiply(cplx *f0, cplx *ft, T weight=1.0)
void cntr::herm_matrix_timestep< T >::Send_timestep(int tstp, int ntau, int size1, int dest, int tag)
void cntr::herm_matrix_timestep< T >::set_les(int i, int j, cplx &x)
void cntr::herm_matrix_timestep< T >::set_les(int i, int j, Matrix &M)
void cntr::herm_matrix_timestep< T >::set_les(int j, Matrix &M)
void cntr::herm_matrix_timestep< T >::set_mat(int i, cplx &x)
void cntr::herm_matrix_timestep< T >::set_mat(int i, Matrix &M)
void cntr::herm_matrix_timestep< T >::set_mat_herm(void)
void cntr::herm_matrix_timestep< T >::set_ret(int i, int j, cplx &x)
void cntr::herm_matrix_timestep< T >::set_ret(int i, int j, Matrix &M)
void cntr::herm_matrix_timestep< T >::set_ret(int j, Matrix &M)
void cntr::herm_matrix_timestep< T >::set_tv(int i, int j, cplx &x)
void cntr::herm_matrix_timestep< T >::set_tv(int i, int j, Matrix &M)
void cntr::herm_matrix_timestep< T >::set_tv(int j, Matrix &M)