cntr::function
typedef std::complex<T> cntr::function< T >::cplx
cplx* cntr::function< T >::data_
Pointer to the function in the Matrix form on the real-time axis ( $f(t)$) ; 'data_+ $ (t+1)\;*$element_size' corresponds to (0,0)-component of $f(t)$.
Referenced by cntr::function< T >::ptr, cntr::function< T >::ptr.
int cntr::function< T >::nt_
Maximum number of the time steps.
Referenced by cntr::function< T >::nt.
int cntr::function< T >::size1_
Number of the colums in the Matrix form.
Referenced by cntr::function< T >::size1.
int cntr::function< T >::size2_
Number of the rows in the Matrix form.
Referenced by cntr::function< T >::size2.
int cntr::function< T >::total_size_
Size of the data stored for the function on the real-time axis including $ t=-1$; $ (n_t + 2)$ * size1 * size2 .
int cntr::function< T >::element_size_
Size of the Matrix form; size1*size2.
void cntr::function< T >::Bcast_timestep(int tstp, int root)
cntr::function< T >::function()
Referenced by cntr::function< T >::function, cntr::function< T >::function, cntr::function< T >::get_matrixelement, cntr::function< T >::incr, cntr::function< T >::left_multiply, cntr::function< T >::operator=, cntr::function< T >::operator=, cntr::function< T >::right_multiply, cntr::function< T >::set_matrixelement.
cntr::function< T >::function(const function &f)
References cntr::function< T >::function.
cntr::function< T >::function(function &&f) noexcept
References cntr::function< T >::function.
cntr::function< T >::function(int nt, int size1, int size2)
References cntr::function< T >::nt, cntr::function< T >::size1, cntr::function< T >::size2.
cntr::function< T >::function(int nt, int size1=1)
References cntr::function< T >::nt, cntr::function< T >::size1.
void cntr::function< T >::get_matrixelement(int i1, int i2, function< T > &g)
References cntr::function< T >::function.
void cntr::function< T >::get_value(int tstp, EigenMatrix &M) const
void cntr::function< T >::incr(function< T > &g, T weight=1.0)
References cntr::function< T >::function.
void cntr::function< T >::left_multiply(cplx *f, T weight=1.0)
void cntr::function< T >::left_multiply(function< T > &f, T weight=1.0)
References cntr::function< T >::function.
int cntr::function< T >::nt(void) const
References cntr::function< T >::nt_.
Referenced by cntr::dyson_timestep_omp, cntr::function< T >::function, cntr::function< T >::function, cntr::function< T >::resize.
function & cntr::function< T >::operator=(const function &f)
References cntr::function< T >::function.
function & cntr::function< T >::operator=(function &&f) noexcept
References cntr::function< T >::function.
cplx & cntr::function< T >::operator[](int t)
References cntr::function< T >::ptr.
const cplx & cntr::function< T >::operator[](int t) const
References cntr::function< T >::ptr.
void cntr::function< T >::print_to_file(const char *file, int precision=16) const
cplx * cntr::function< T >::ptr(int t)
References cntr::function< T >::data_.
Referenced by cntr::dyson_timestep_omp, cntr::function< T >::operator[], cntr::function< T >::operator[].
const cplx * cntr::function< T >::ptr(int t) const
References cntr::function< T >::data_.
void cntr::function< T >::read_from_file(const char *file)
void cntr::function< T >::read_from_file(int nt1, const char *file)
void cntr::function< T >::read_from_hdf5(const char *filename, const char *groupname)
void cntr::function< T >::read_from_hdf5(hid_t group_id)
void cntr::function< T >::read_from_hdf5(hid_t group_id, const char *groupname)
void cntr::function< T >::read_from_hdf5(int nt1, const char *filename, const char *groupname)
void cntr::function< T >::read_from_hdf5(int nt1, hid_t group_id)
void cntr::function< T >::read_from_hdf5(int nt1, hid_t group_id, const char *groupname)
void cntr::function< T >::resize(int nt, int size1)
References cntr::function< T >::nt, cntr::function< T >::size1.
void cntr::function< T >::right_multiply(cplx *f, T weight=1.0)
void cntr::function< T >::right_multiply(function< T > &f, T weight=1.0)
References cntr::function< T >::function.
void cntr::function< T >::set_constant(cplx *f0)
void cntr::function< T >::set_constant(EigenMatrix &M)
void cntr::function< T >::set_matrixelement(int i1, int i2, function &g, int j1, int j2)
References cntr::function< T >::function.
void cntr::function< T >::set_matrixelement(int tstp, int i1, int i2, EigenMatrix &M, int j1, int j2)
void cntr::function< T >::set_value(int tstp, cplx x)
void cntr::function< T >::set_value(int tstp, EigenMatrix &M)
void cntr::function< T >::set_zero(void)
int cntr::function< T >::size1(void) const
References cntr::function< T >::size1_.
Referenced by cntr::dyson_timestep_omp, cntr::function< T >::function, cntr::function< T >::function, cntr::function< T >::resize.
int cntr::function< T >::size2(void) const
References cntr::function< T >::size2_.
Referenced by cntr::function< T >::function.
void cntr::function< T >::smul(T weight)
void cntr::function< T >::write_to_hdf5(const char *filename, const char *groupname) const
void cntr::function< T >::write_to_hdf5(hid_t group_id) const
void cntr::function< T >::write_to_hdf5(hid_t group_id, const char *groupname) const
cntr::function< T >::~function()
int cntr::function< T >::element_size(void) const