cntr::herm_matrix_timestep_view
typedef std::complex<T> cntr::herm_matrix_timestep_view< T >::cplx
typedef T cntr::herm_matrix_timestep_view< T >::scalar_type
int cntr::herm_matrix_timestep_view< T >::element_size_
Size of the Matrix form; size1*size2.
std::complex<T>* cntr::herm_matrix_timestep_view< T >::les_
Pointer to the lesser component. 'less_+ $t \;*$ element_size' corresponds to $(0,0)$-component of $ G^<(t,tstp) $
std::complex<T>* cntr::herm_matrix_timestep_view< T >::mat_
Pointer to the Matsubara component. 'mat_+ $\tau \;*$ element_size' corresponds to $(0,0)$-component of $ G^M(\tau) $
int cntr::herm_matrix_timestep_view< T >::ntau_
Number of the time grids on the Matsubara axis.
std::complex<T>* cntr::herm_matrix_timestep_view< T >::ret_
Pointer to the retarded component. 'ret_+ $t \;*$ element_size' corresponds to $(0,0)$-component of $ G^R(tstp,t) $
int cntr::herm_matrix_timestep_view< T >::sig_
Bose = +1, Fermi =-1.
int cntr::herm_matrix_timestep_view< T >::size1_
Number of the colums in the Matrix form.
int cntr::herm_matrix_timestep_view< T >::size2_
Number of the rows in the Matrix form.
int cntr::herm_matrix_timestep_view< T >::tstp_
time step.
std::complex<T>* cntr::herm_matrix_timestep_view< T >::tv_
Pointer to the left-mixing component. 'tv_+ $\tau \;*$ element_size' corresponds to $(0,0)$-component of $ G^\rceil(tstp,\tau) $
void cntr::herm_matrix_timestep_view< T >::Bcast_timestep(int tstp, int root)
void cntr::herm_matrix_timestep_view< T >::density_matrix(int tstp, Matrix &M)
void cntr::herm_matrix_timestep_view< T >::density_matrix(int tstp, std::complex< T > &M)
void cntr::herm_matrix_timestep_view< T >::get_data(GG &g)
void cntr::herm_matrix_timestep_view< T >::get_data(herm_matrix_timestep_view< T > &g)
void cntr::herm_matrix_timestep_view< T >::get_data(std::complex< T > *ret, std::complex< T > *les, std::complex< T > *tv, std::complex< T > *mat)
void cntr::herm_matrix_timestep_view< T >::get_timestep(int tstp, herm_matrix_timestep< T > &timestep)
cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view()
Referenced by cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view, cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view, cntr::herm_matrix_timestep_view< T >::operator=.
cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view(const herm_matrix_timestep_view &g)
References cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view.
cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view(herm_matrix_timestep< T > &g)
cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view(int tstp, herm_matrix< T > &g, bool check_assert=true)
References cntr::herm_matrix_timestep_view< T >::tstp.
cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view(int tstp, herm_matrix_timestep< T > &g, bool check_assert=true)
References cntr::herm_matrix_timestep_view< T >::tstp.
cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view(int tstp, herm_matrix_timestep_view< T > &g)
References cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view, cntr::herm_matrix_timestep_view< T >::tstp.
cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view(int tstp, int ntau, int size1, int size2, int sig)
References cntr::herm_matrix_timestep_view< T >::ntau, cntr::herm_matrix_timestep_view< T >::sig, cntr::herm_matrix_timestep_view< T >::size1, cntr::herm_matrix_timestep_view< T >::size2, cntr::herm_matrix_timestep_view< T >::tstp.
void cntr::herm_matrix_timestep_view< T >::incr_timestep(GG &g, std::complex< T > alpha)
void cntr::herm_matrix_timestep_view< T >::incr_timestep(GG &g, T alpha)
void cntr::herm_matrix_timestep_view< T >::incr_timestep(herm_matrix_timestep_view< T > &g, std::complex< T > alpha)
void cntr::herm_matrix_timestep_view< T >::incr_timestep(herm_matrix_timestep_view< T > &g, T alpha)
void cntr::herm_matrix_timestep_view< T >::left_multiply(int tstp, function< T > &ft, T weight=1.0)
void cntr::herm_matrix_timestep_view< T >::left_multiply_hermconj(int tstp, function< T > &ft, T weight=1.0)
int cntr::herm_matrix_timestep_view< T >::ntau(void) const
Referenced by cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view, cntr::herm_matrix_timestep_view< T >::set_to_data.
herm_matrix_timestep_view & cntr::herm_matrix_timestep_view< T >::operator=(const herm_matrix_timestep_view &g)
References cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view.
void cntr::herm_matrix_timestep_view< T >::read_from_hdf5(const char *filename, const char *groupname)
void cntr::herm_matrix_timestep_view< T >::read_from_hdf5(hid_t group_id)
void cntr::herm_matrix_timestep_view< T >::read_from_hdf5(hid_t group_id, const char *groupname)
void cntr::herm_matrix_timestep_view< T >::Recv_timestep(int tstp, int root, int tag)
void cntr::herm_matrix_timestep_view< T >::Reduce_timestep(int tstp, int root)
void cntr::herm_matrix_timestep_view< T >::right_multiply(int tstp, function< T > &ft, T weight=1.0)
void cntr::herm_matrix_timestep_view< T >::right_multiply_hermconj(int tstp, function< T > &ft, T weight=1.0)
void cntr::herm_matrix_timestep_view< T >::Send_timestep(int tstp, int dest, int tag)
void cntr::herm_matrix_timestep_view< T >::set_matrixelement(int i1, int i2, GG &g, int j1, int j2)
void cntr::herm_matrix_timestep_view< T >::set_matrixelement(int i1, int i2, herm_matrix_timestep_view< T > &g, int j1, int j2)
void cntr::herm_matrix_timestep_view< T >::set_timestep(int tstp, herm_matrix< T > &g1)
void cntr::herm_matrix_timestep_view< T >::set_timestep(int tstp, herm_matrix_timestep< T > &g1)
void cntr::herm_matrix_timestep_view< T >::set_timestep_zero(int tstp)
void cntr::herm_matrix_timestep_view< T >::set_to_data(herm_matrix_timestep< T > &g)
void cntr::herm_matrix_timestep_view< T >::set_to_data(int tstp, herm_matrix< T > &g)
References cntr::herm_matrix_timestep_view< T >::tstp.
void cntr::herm_matrix_timestep_view< T >::set_to_data(std::complex< T > *data, int tstp, int ntau, int size, int sig)
References cntr::herm_matrix_timestep_view< T >::ntau, cntr::herm_matrix_timestep_view< T >::sig, cntr::herm_matrix_timestep_view< T >::tstp.
int cntr::herm_matrix_timestep_view< T >::sig(void) const
Referenced by cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view, cntr::herm_matrix_timestep_view< T >::set_to_data.
int cntr::herm_matrix_timestep_view< T >::size1(void) const
Referenced by cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view.
int cntr::herm_matrix_timestep_view< T >::size2(void) const
Referenced by cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view.
void cntr::herm_matrix_timestep_view< T >::smul(T alpha)
int cntr::herm_matrix_timestep_view< T >::tstp(void) const
Referenced by cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view, cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view, cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view, cntr::herm_matrix_timestep_view< T >::herm_matrix_timestep_view, cntr::herm_matrix_timestep_view< T >::set_to_data, cntr::herm_matrix_timestep_view< T >::set_to_data.
void cntr::herm_matrix_timestep_view< T >::write_to_hdf5(const char *filename, const char *groupname)
void cntr::herm_matrix_timestep_view< T >::write_to_hdf5(hid_t group_id)
void cntr::herm_matrix_timestep_view< T >::write_to_hdf5(hid_t group_id, const char *groupname)
cntr::herm_matrix_timestep_view< T >::~herm_matrix_timestep_view()
std::complex< T > cntr::herm_matrix_timestep_view< T >::density_matrix(int tstp)
void cntr::herm_matrix_timestep_view< T >::get_les(int i, int j, Matrix &M)
void cntr::herm_matrix_timestep_view< T >::get_mat(int i, Matrix &M)
void cntr::herm_matrix_timestep_view< T >::get_matminus(int i, Matrix &M)
void cntr::herm_matrix_timestep_view< T >::get_ret(int i, int j, Matrix &M)
void cntr::herm_matrix_timestep_view< T >::get_tv(int i, int j, Matrix &M)
void cntr::herm_matrix_timestep_view< T >::left_multiply(int tstp, std::complex< T > *f0, std::complex< T > *ft, T weight=1.0)
std::complex< T > * cntr::herm_matrix_timestep_view< T >::lesptr(int i)
std::complex< T > * cntr::herm_matrix_timestep_view< T >::matptr(int i)
void cntr::herm_matrix_timestep_view< T >::MPI_Reduce(int root)
std::complex< T > * cntr::herm_matrix_timestep_view< T >::retptr(int i)
void cntr::herm_matrix_timestep_view< T >::right_multiply(int tstp, std::complex< T > *f0, std::complex< T > *ft, T weight=1.0)
void cntr::herm_matrix_timestep_view< T >::set_les(int i, int j, Matrix &M)
void cntr::herm_matrix_timestep_view< T >::set_mat(int i, Matrix &M)
void cntr::herm_matrix_timestep_view< T >::set_ret(int i, int j, Matrix &M)
void cntr::herm_matrix_timestep_view< T >::set_tv(int i, int j, Matrix &M)
std::complex< T > * cntr::herm_matrix_timestep_view< T >::tvptr(int i)