cntr::distributed_timestep_array
distributed_array<std::complex<T> > cntr::distributed_timestep_array< T >::data_
Pointer to the contiguous data
std::vector<cntr::herm_matrix_timestep_view<T> > cntr::distributed_timestep_array< T >::G_
Vector of views to the herm_matrix_timestep
int cntr::distributed_timestep_array< T >::n_
Number of blocks
int cntr::distributed_timestep_array< T >::nt_
The maximum allowed timestep (set by size of data_)
int cntr::distributed_timestep_array< T >::ntasks_
MPI size if MPI is defined, else 1
int cntr::distributed_timestep_array< T >::ntau_
Number of imaginary time step
int cntr::distributed_timestep_array< T >::sig_
Fermion(boson)=-1(1)
int cntr::distributed_timestep_array< T >::size_
Size of green's function
int cntr::distributed_timestep_array< T >::tid_
MPI rank if MPI is defined, else 0
int cntr::distributed_timestep_array< T >::tstp_
Current timestep
void cntr::distributed_timestep_array< T >::clear(void)
distributed_array< std::complex< T > > cntr::distributed_timestep_array< T >::data(void) const
cntr::distributed_timestep_array< T >::distributed_timestep_array()
Referenced by cntr::distributed_timestep_array< T >::distributed_timestep_array, cntr::distributed_timestep_array< T >::operator=.
cntr::distributed_timestep_array< T >::distributed_timestep_array(const distributed_timestep_array &a)
References cntr::distributed_timestep_array< T >::distributed_timestep_array.
cntr::distributed_timestep_array< T >::distributed_timestep_array(int n, int nt, int ntau, int size, int sig, bool mpi)
References cntr::distributed_timestep_array< T >::n, cntr::distributed_timestep_array< T >::nt, cntr::distributed_timestep_array< T >::ntau, cntr::distributed_timestep_array< T >::sig, cntr::distributed_timestep_array< T >::size.
cntr::herm_matrix_timestep_view< T > & cntr::distributed_timestep_array< T >::G(int j)
std::vector< cntr::herm_matrix_timestep_view< T > > cntr::distributed_timestep_array< T >::G(void) const
void cntr::distributed_timestep_array< T >::mpi_bcast_all(void)
void cntr::distributed_timestep_array< T >::mpi_bcast_block(int j)
int cntr::distributed_timestep_array< T >::n(void) const
Referenced by cntr::distributed_timestep_array< T >::distributed_timestep_array.
int cntr::distributed_timestep_array< T >::nt(void) const
Referenced by cntr::distributed_timestep_array< T >::distributed_timestep_array.
int cntr::distributed_timestep_array< T >::ntasks(void) const
int cntr::distributed_timestep_array< T >::ntau(void) const
Referenced by cntr::distributed_timestep_array< T >::distributed_timestep_array.
distributed_timestep_array< T > & cntr::distributed_timestep_array< T >::operator=(const distributed_timestep_array &a)
References cntr::distributed_timestep_array< T >::distributed_timestep_array.
void cntr::distributed_timestep_array< T >::reset_tstp(int tstp)
References cntr::distributed_timestep_array< T >::tstp.
int cntr::distributed_timestep_array< T >::sig(void) const
Referenced by cntr::distributed_timestep_array< T >::distributed_timestep_array.
int cntr::distributed_timestep_array< T >::size(void) const
Referenced by cntr::distributed_timestep_array< T >::distributed_timestep_array.
int cntr::distributed_timestep_array< T >::tid(void) const
int cntr::distributed_timestep_array< T >::tstp(void) const
Referenced by cntr::distributed_timestep_array< T >::reset_tstp.
cntr::distributed_timestep_array< T >::~distributed_timestep_array()