integration::Integrator
T* integration::Integrator< T >::bd_weights_
T* integration::Integrator< T >::gregory_omega_
T* integration::Integrator< T >::gregory_weights_
int integration::Integrator< T >::k_
T* integration::Integrator< T >::poly_differentiation_
T* integration::Integrator< T >::poly_integration_
T* integration::Integrator< T >::poly_interpolation_
T* integration::Integrator< T >::rcorr_
T integration::Integrator< T >::bd_weights(int l) const
Returns the the backwards differencing coefficients.
Purpose Backward differentiation formula of order $k+1$ is given by \begin{align*} \frac{d}{d x}f(x)\big|_{x_i} = \frac{1}{h}\sum^{k+1}_{l=0} c_l\, f(x_{i-l}) \end{align*} The weights are related to the poly_differentiation weights. bd_weights returns the coefficient $c_l$ for given $l$. l Index of weight.
int integration::Integrator< T >::get_k(void) const
Returns the order $k$ of the integrator class.
Purpose Returns the order $k$ of the integrator class.
T integration::Integrator< T >::gregory_omega(int j) const
Returns the Gregory weights at the integral boundaries (see gregory_weights).
Purpose Returns the weight $\omega_j$ needed close to the integral boundaries (see gregory weights). j Index of the Gregory weight.
T integration::Integrator< T >::gregory_weights(int n, int j) const
Returns the Gregory weights for integration.
Purpose The Gregory integration formula of order $k$ is defined by \begin{align*} \int^{x_m}_0 dx \, f(x) = \sum^{\mathrm{max}(k,m)}_{l=0} w_{m,l}\, f(x_l) \end{align*} For $m > 2 k$, the weights have a simpler form: \begin{align*} w_{m,j} = \begin{cases} \omega_j & : j \le k \\ 1 & : k < j < m-k \\ \omega_{m-j} & : j \ge m-k \end{cases} \end{align*} Here, $\omega_j$ are tabulated weights for $0 \le j \le k$. gregory_weights returns $w_{n,j}$ for given $n, j$. n Integration runs up to $x_n$. j Index of the Gregory weight.
M integration::Integrator< T >::integrate(const std::vector< M > &f, int n) const
Integrates a function using Gregory quadrature.
Purpose Computes the integral \begin{align*} \int^{x_n}_0 dx \, f(x) = h\sum^{\mathrm{max}(k,m)}_{l=0} w_{n,l}\, f(x_l) \end{align*} The function $f$ represents any class M for which M=0 is defined. f A standard vector of class M with at least lenght n+1. n The index of the upper integral bound.
integration::Integrator< T >::Integrator(const Integrator &I)
References integration::I, integration::Integrator< T >::Integrator.
integration::Integrator< T >::Integrator(int k=0)
Initializes the Integrator class for a given order k.
Purpose Initializes the Integrator class for given order $k$ between 1 and 8. If $k>5$, Gregory integration up to order $k$ is used, while all other operations are limited to maximum order 5. k The order of the weights.
References integration::Integrator< T >::k.
Referenced by integration::Integrator< T >::Integrator, integration::Integrator< T >::operator=.
int integration::Integrator< T >::k(void) const
Returns the order $k$ of the integrator class.
Purpose Returns the order $k$ of the integrator class.
Referenced by integration::Integrator< T >::Integrator.
Integrator & integration::Integrator< T >::operator=(const Integrator &I)
References integration::I, integration::Integrator< T >::Integrator.
T integration::Integrator< T >::poly_differentiation(int i, int l) const
Returns the the weight needed for polynomial differentiation.
Purpose Assuming the function $f(x)$ is given through points $\{(x_l,f(x_l),l=0,\dots,k)\}$\ with $x_{l+1}-x_{l}=h$, polynomial differentiation is defined by \begin{align*} \frac{d}{dx}f(x)\big|_{x_i} = \frac{1}{h}\sum^k_{l=0} c_{i,l}\, f(x_l) \end{align*} poly_differentiation returns the coefficient $c_{i,l}$ for given indicies $i,l$. i First index of coefficients. l Second index of coefficients.
T integration::Integrator< T >::poly_integration(int i, int j, int l) const
Returns the the weight needed for polynomial integration.
Purpose Assuming the function $f(x)$ is given through points $\{(x_l,f(x_l),l=0,\dots,k)\}$, polynomial interpolation is defined by \begin{align*} \int^{x_j}_{x_i}dx \, f(x) = h \sum^k_{l=0} w_{i,j,l}\, f(x_l) \end{align*} This is needed for computing integrals over small intervals with less grid points than needed for Gregory quadrature. Polynomial integration is used for the polynomial collocation method for solving the Volterra integral equations. poly_integration returns the weight $w_{i,j,l}$ for given indices. i Index of lower integral bound. j Index of upper integral bound. l Index of weight.
T integration::Integrator< T >::poly_interpolation(int alpha, int l) const
Returns the the weight needed for polynomial interpolation.
Purpose The $k$-th order approximation polynomial $P(x)$ through function values $\{(x_l,f(x_l),l=0,\dots,k)\}$ with $x_{l+1}-x_{l}=h$ is given by \begin{align*} P(x) = \sum^k_{\alpha=0}\sum^k_{l=0} c_{\alpha,l}\, \left(\frac{x}{h}\right)^\alpha f(x_l) \end{align*} poly_interpolation returns the coeffient $c_{\alpha,l}$ for given indicies $\alpha,l$. alpha First index of coefficients. l Second index of coefficients.
T integration::Integrator< T >::rcorr(int m, int j, int l) const
Returns the special quadrature weights for computing integrals on the Matsubara axis.
Purpose For calculation integrals on the Matsubara axis of the type \begin{align*} R(\tau_m) = \int^{\tau_m}_0 d\tau\, A(\tau_m-\tau)B(\tau) \ , \end{align*} Gregory quadrature can only be used for $m \ge k$. For $m < k$, special weights are needed, since the Matsubara Green's functions can not contuinuously be continued to $\tau <0$ and $\tau >\beta$. Using two-dimensional polynomial interpolation, one can represent the convolution integral by \begin{align*} R(\tau_m) = \Delta\tau\sum^k_{j,l=0} w_{m,j,l}\, A(\tau_j) B(\tau_l) \ . \end{align*} rcorr returns the quadrature weights $w_{m,j,l}$ for given indices. m The index of the upper integration bound. j The second indes of the weights. l The second indes of the weights.
integration::Integrator< T >::~Integrator()