cntr::distributed_array
int cntr::distributed_array< T >::blocksize_
Size of one element in the block. In combination with distributed_timestep_array this number is changed with increasing timesteps.
T* cntr::distributed_array< T >::data_
Pointer to the contiguous data
int cntr::distributed_array< T >::maxlen_
Size of one element in the block. In combination with distributed_timestep_array this number is fixed to maximal length
int cntr::distributed_array< T >::n_
Number of data blocks
int cntr::distributed_array< T >::ntasks_
mpi size if MPI is defined, else 1
int cntr::distributed_array< T >::tid_
mpi rank if MPI is defined, else 0
std::vector<int> cntr::distributed_array< T >::tid_map_
Returns the rank owning block j $ tid_map(j) = tid_$.
T * cntr::distributed_array< T >::block(int j)
int cntr::distributed_array< T >::blocksize(void) const
Referenced by cntr::distributed_array< T >::reset_blocksize.
void cntr::distributed_array< T >::clear(void)
T * cntr::distributed_array< T >::data(void) const
cntr::distributed_array< T >::distributed_array()
Referenced by cntr::distributed_array< T >::distributed_array, cntr::distributed_array< T >::operator=.
cntr::distributed_array< T >::distributed_array(const distributed_array &g)
References cntr::distributed_array< T >::distributed_array.
cntr::distributed_array< T >::distributed_array(int n, int maxlen, bool mpi)
References cntr::distributed_array< T >::maxlen, cntr::distributed_array< T >::n.
int cntr::distributed_array< T >::firstblock_rank(void)
int cntr::distributed_array< T >::maxlen(void) const
Referenced by cntr::distributed_array< T >::distributed_array.
void cntr::distributed_array< T >::mpi_bcast_all(void)
void cntr::distributed_array< T >::mpi_bcast_all(void)
void cntr::distributed_array< T >::mpi_bcast_block(int j)
void cntr::distributed_array< T >::mpi_bcast_block(int j)
void cntr::distributed_array< T >::mpi_gather(int dest)
void cntr::distributed_array< T >::mpi_gather(void)
void cntr::distributed_array< T >::mpi_send_block(int j, int dest)
int cntr::distributed_array< T >::n(void) const
Referenced by cntr::distributed_array< T >::distributed_array.
int cntr::distributed_array< T >::ntasks(void) const
int cntr::distributed_array< T >::numblock_rank(void)
distributed_array & cntr::distributed_array< T >::operator=(const distributed_array &g)
References cntr::distributed_array< T >::distributed_array.
bool cntr::distributed_array< T >::rank_owns(int k) const
References cntr::distributed_array< T >::tid, cntr::distributed_array< T >::tid_map.
void cntr::distributed_array< T >::reset_blocksize(int blocksize)
References cntr::distributed_array< T >::blocksize.
int cntr::distributed_array< T >::tid(void) const
Referenced by cntr::distributed_array< T >::rank_owns.
std::vector< int > cntr::distributed_array< T >::tid_map(void) const
Referenced by cntr::distributed_array< T >::rank_owns.
cntr::distributed_array< T >::~distributed_array()