ness2::fft_array
int ness2::fft_array::element_size_
Stride for each transform (`size1_ * size1_).
Referenced by get_element, left_multiply, left_multiply_hermconj, right_multiply, right_multiply_hermconj, set_element.
fftw_complex* ness2::fft_array::freq_
Pointer to frequency-domain data.
Referenced by get_element, left_multiply, left_multiply_hermconj, right_multiply, right_multiply_hermconj, set_element.
int ness2::fft_array::Nft_
Number of time samples per transform.
Referenced by ness2::compute_lesser, get_element, left_multiply, left_multiply_hermconj, right_multiply, right_multiply_hermconj, set_element.
int ness2::fft_array::size1_
Logical size (stride = size1_ * size1_).
Referenced by ness2::compute_lesser, get_element, ness2::green_equilibrium_ret_ness_adaptive, left_multiply, left_multiply_hermconj, right_multiply, right_multiply_hermconj, set_element.
fftw_complex* ness2::fft_array::time_
Pointer to time-domain data.
Referenced by get_element, left_multiply, left_multiply_hermconj, right_multiply, right_multiply_hermconj, set_element.
fftw_plan ness2::fft_array::plan_back_
FFTW backward plan.
fftw_plan ness2::fft_array::plan_for_
FFTW forward plan.
ness2::fft_array::fft_array(const fft_array &other)
Copy constructor.
References fft_array.
ness2::fft_array::fft_array(int Nft, int size, unsigned FFTW_FLAG=FFTW_ESTIMATE)
Constructor.
Nft FFT length size Logical size (stride = size x size) FFTW_FLAG FFTW planning flag (e.g., FFTW_ESTIMATE)
Referenced by fft_array, incr, operator=, set_matrixelement.
void ness2::fft_array::fft_to_freq()
Performs a forward FFT (time domain → frequency domain). This is because plan_back_ was created with FFTW_FORWARD. $ X[k] = \sum_{n=0}^{N_{ft}-1} x[n] \cdot \exp(-2\pi i \cdot k \cdot n / N_{ft}) $ Note: This is the standard DFT definition (no scaling).
void ness2::fft_array::fft_to_time()
Performs an inverse FFT (frequency domain → time domain). This is because plan_for_ was created with FFTW_BACKWARD. $ x[n] = \sum_{k=0}^{N_{ft}-1} X[k] \cdot \exp(+2\pi i \cdot k \cdot n / N_{ft}) $ Note: FFTW does NOT normalize this, so the result will be scaled by $ N_{ft} $ . You may need to manually divide by $ N_{ft} $ if you want the exact inverse.
void ness2::fft_array::get_element(int t, cplx &val, fft_domain type) const
Get $ {\tt val} = A(t) $ from this fft_array $ A $ at time or frequency index $ t $ (with periodic wrapping).
Only valid when $ \text{size1}\_ = 1 $ (scalar case). If $ t < 0 $ or $ t \geq N_{ft} $, it is automatically wrapped periodically: $ t \equiv t \bmod N_{ft} $ in $ [0, N_{ft} - 1] $. t Time index (wrapped periodically). val Complex scalar to retrieve. type Whether to read from time or frequency array (fft_domain::time or fft_domain::freq).
void ness2::fft_array::get_element(int t, MatrixType &M, fft_domain type) const
Get $ M = A(t) $ from this fft_array $ A $ at or frequency time index $ t $ (with periodic wrapping).
If $ t < 0 $ or $ t \geq N_{ft} $, it is automatically wrapped periodically: $ t \equiv t \bmod N_{ft} $ in $ [0, N_{ft} - 1] $. MatrixType Any Eigen-compatible complex matrix type. t Time index (wrapped periodically). M Matrix to fill with the values at time index $ t $. type Whether to read from time or frequency array (fft_domain::time or fft_domain::freq).
References element_size_, freq_, Nft_, size1_, ness2::time, time_.
void ness2::fft_array::incr(const fft_array &B, std::complex< double > alpha, fft_domain type)
Increment this fft_array $ A $ by another scaled array $ B $: $ A \to A + \alpha \cdot B $.
B Another fft_array with matching dimensions. alpha Complex scaling factor. type Whether to operate on time or frequency arrays (fft_domain::time or fft_domain::freq).
References fft_array.
void ness2::fft_array::left_multiply(const MatrixType &M, fft_domain type)
Multiply each time/frequency matrix of this fft_array $ A $ from the left by a complex matrix $ M $: $ A(t) \to M \cdot A(t) $.
definitions of templated member functions: MatrixType Any Eigen-compatible complex matrix type. M The matrix to left-multiply with (must be size1_ × size1_) type Whether to apply to time or frequency domain data (fft_domain::time or fft_domain::freq).
References element_size_, freq_, Nft_, size1_, smul, ness2::time, time_.
void ness2::fft_array::left_multiply_hermconj(const MatrixType &M, fft_domain type)
Multiply each time/frequency matrix of this fft_array $ A $ from the left by the hermitian conjugate of a complex matrix $ M $: $ A(t) \to M^\dagger \cdot A(t) $.
MatrixType Any Eigen-compatible complex matrix type. M The matrix to left-multiply with (must be size1_ × size1_) type Whether to apply to time or frequency domain data (fft_domain::time or fft_domain::freq).
References element_size_, freq_, Nft_, size1_, smul, ness2::time, time_.
fft_array & ness2::fft_array::operator=(const fft_array &other)
Copy assignment operator.
References fft_array.
void ness2::fft_array::print_to_file(const std::string &filename, int precision=12) const
Print the time and frequency arrays to a plain text file.
Outputs: Header: # Nft size1_ precision Blocks: time and frequency (each with one line per $ t $). filename Path to the text file. precision Number of digits for real/imaginary part (default: 12).
void ness2::fft_array::read_from_file(const std::string &filename, unsigned FFTW_FLAG=FFTW_ESTIMATE)
Read the time and frequency arrays from a plain text file written with print_to_file.
Resizes internal arrays if needed using the provided FFTW_FLAG. filename Path to the text file. FFTW_FLAG FFTW planning flag to use if resizing (default: FFTW_ESTIMATE).
void ness2::fft_array::read_from_hdf5(hid_t group_id, unsigned FFTW_FLAG=FFTW_ESTIMATE)
Read the fft_array data (time and frequency arrays) from an HDF5 group.
If the stored array dimensions differ from the current object, automatically resizes the object using the provided FFTW_FLAG. group_id HDF5 group identifier. FFTW_FLAG FFTW planning flag to use if resizing (default: FFTW_ESTIMATE).
void ness2::fft_array::resize(int new_Nft, int new_size1, unsigned FFTW_FLAG=FFTW_ESTIMATE)
Resize the fft_array and rebuild FFTW plans.
Frees any existing memory and FFTW plans, then allocates new arrays and creates new FFTW plans for the given sizes. After calling, the array is reset and ready for use. new_Nft New number of time samples per transform. new_size1 New matrix dimension (new_size1 × new_size1). FFTW_FLAG FFTW planning flag (default: FFTW_ESTIMATE).
void ness2::fft_array::right_multiply(const MatrixType &M, fft_domain type)
Multiply each time/frequency matrix of this fft_array $ A $ from the right by a complex matrix $ M $: $ A(t) \to A(t) \cdot M $.
MatrixType Any Eigen-compatible complex matrix type. M The matrix to right-multiply with (must be size1_ xsize1_) type Whether to apply to time or frequency domain data (fft_domain::time or fft_domain::freq).
References element_size_, freq_, Nft_, size1_, smul, ness2::time, time_.
void ness2::fft_array::right_multiply_hermconj(const MatrixType &M, fft_domain type)
Multiply each time/frequency matrix of this fft_array $ A $ from the right by the hermitian conjugate of a complex matrix $ M $: $ A(t) \to A(t) \cdot M^\dagger $.
MatrixType Any Eigen-compatible complex matrix type. M The matrix to left-multiply with (must be size1_ × size1_) type Whether to apply to time or frequency domain data (fft_domain::time or fft_domain::freq).
References element_size_, freq_, Nft_, size1_, smul, ness2::time, time_.
void ness2::fft_array::set_element(int t, const MatrixType &M, fft_domain type)
Set this fft_array $ A $ to $ A(t) $ = $ M $ at time or frequency index $ t $ (with periodic wrapping).
If $ t < 0 $ or $ t \geq N_{ft} $, it is automatically wrapped periodically: $ t \equiv t \bmod N_{ft} $ in $ [0, N_{ft} - 1] $. MatrixType Any Eigen-compatible complex matrix type. t Time index (wrapped periodically). M Matrix to assign. type Whether to apply to time or frequency array (fft_domain::time or fft_domain::freq).
References element_size_, freq_, Nft_, size1_, ness2::time, time_.
Referenced by ness2::compute_lesser, ness2::green_equilibrium_ret_ness_adaptive.
void ness2::fft_array::set_element(int t, cplx val, fft_domain type)
Set this fft_array $ A $ to $ A(t) = \tt{val} $ at time or frequency index $ t $ (with periodic wrapping).
Only valid when $ \text{size1}\_ = 1 $ (scalar case). If $ t < 0 $ or $ t \geq N_{ft} $, it is automatically wrapped periodically: $ t \equiv t \bmod N_{ft} $ in $ [0, N_{ft} - 1] $. t Time index (wrapped periodically). val Complex scalar to assign. type Whether to apply to time or frequency array (fft_domain::time or fft_domain::freq).
void ness2::fft_array::set_matrixelement(int i1, int i2, const fft_array &B, int j1, int j2, fft_domain type)
Set one matrix element's time or frequency series of this fft_array $ A $ from another fft_array $ B $.
This sets $ A(i_1, i_2)(t) = B(j_1, j_2)(t) $ across all times or frequencies. i1 Row index in $ A(i_1, i_2) $. i2 Column index in $ A(i_1, i_2) $. B Source fft_array. j1 Row index in $ B(j_1, j_2) $. j2 Column index in $ B(j_1, j_2) $. type Whether to operate on time or frequency arrays (fft_domain::time or fft_domain::freq).
References fft_array.
void ness2::fft_array::set_zero(fft_domain type)
Set all elements of either the time or frequency array to zero.
type Indicates whether to clear the time or frequency array.
Referenced by ness2::compute_lesser, ness2::green_equilibrium_ness_bose, ness2::green_equilibrium_ness_fermi.
void ness2::fft_array::smul(std::complex< double > alpha, fft_domain type)
Scale this fft_array $ A $ in-place by a complex scalar $ \alpha $: $ A \to \alpha \cdot A $.
alpha Complex scaling factor. type Indicates whether to scale time or frequency array (fft_domain::time or fft_domain::freq).
Referenced by left_multiply, left_multiply_hermconj, right_multiply, right_multiply_hermconj.
void ness2::fft_array::write_to_hdf5(hid_t group_id) const
Write the fft_array data (time and frequency arrays) to an HDF5 group.
Stores attributes for Nft_, size1_, and element_size_, and datasets for the time_ and freq_ arrays as 3D arrays of shape [Nft_, size1_, size1_]. group_id HDF5 group identifier.
ness2::fft_array::~fft_array()
Destructor.