cntr::herm_matrix_timestep_moving
typedef std::complex<T> cntr::herm_matrix_timestep_moving< T >::cplx
typedef T cntr::herm_matrix_timestep_moving< T >::scalar_type
cplx* cntr::herm_matrix_timestep_moving< T >::data_
Pointer to the data for the time step (t0).
int cntr::herm_matrix_timestep_moving< T >::element_size_
Size of the Matrix form; size1*size2.
cplx* cntr::herm_matrix_timestep_moving< T >::les_
Pointer to the lesser part for the time step (t0). 'data_+ $(tc+1+tc)$ * element_size' correponds to (0,0)-component of $ G^<(t0,t0-tc)$ and 'les_(tc)'.
cplx* cntr::herm_matrix_timestep_moving< T >::ret_
Pointer to the retarded part for the time step (t0). 'data_+ $tc$ * element_size' correponds to (0,0)-component of $ G^<(t0,t0-tc)$ and 'ret_(tc)'.
int cntr::herm_matrix_timestep_moving< T >::sig_
Bose = +1, Fermi =-1.
int cntr::herm_matrix_timestep_moving< T >::size1_
Number of the colums in the Matrix form.
int cntr::herm_matrix_timestep_moving< T >::size2_
Number of the rows in the Matrix form.
int cntr::herm_matrix_timestep_moving< T >::tc_
Given cutoff time tc
void cntr::herm_matrix_timestep_moving< T >::clear_timestep(void)
Clears the stored timestep data (set to zero).
void cntr::herm_matrix_timestep_moving< T >::density_matrix(Matrix &M)
std::complex< T > cntr::herm_matrix_timestep_moving< T >::density_matrix(void)
int cntr::herm_matrix_timestep_moving< T >::element_size(void) const
Returns the time elemet size = size1*size2.
void cntr::herm_matrix_timestep_moving< T >::get_gtr(int deltj, cplx &x)
void cntr::herm_matrix_timestep_moving< T >::get_gtr(int deltj, Matrix &M)
void cntr::herm_matrix_timestep_moving< T >::get_les(int deltj, cplx &x)
void cntr::herm_matrix_timestep_moving< T >::get_les(int deltj, Matrix &M)
void cntr::herm_matrix_timestep_moving< T >::get_ret(int deltj, cplx &x)
void cntr::herm_matrix_timestep_moving< T >::get_ret(int deltj, Matrix &M)
cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving()
Referenced by cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving, cntr::herm_matrix_timestep_moving< T >::incr_timestep, cntr::herm_matrix_timestep_moving< T >::operator=, cntr::herm_matrix_timestep_moving< T >::set_matrixelement, cntr::herm_matrix_timestep_moving< T >::set_timestep.
cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving(const herm_matrix_timestep_moving &g)
References cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving.
cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving(herm_matrix_moving< T > &g, int delti_g)
cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving(int tc, int size1=1, int sig=-1)
References cntr::herm_matrix_timestep_moving< T >::sig, cntr::herm_matrix_timestep_moving< T >::size1, cntr::herm_matrix_timestep_moving< T >::tc.
void cntr::herm_matrix_timestep_moving< T >::incr_timestep(herm_matrix_moving< T > &g, int delti_g, cplx alpha)
void cntr::herm_matrix_timestep_moving< T >::incr_timestep(herm_matrix_timestep_moving< T > &g, cplx alpha)
References cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving.
void cntr::herm_matrix_timestep_moving< T >::incr_timestep(herm_matrix_timestep_moving_view< T > &g, cplx alpha)
void cntr::herm_matrix_timestep_moving< T >::left_multiply(function_moving< T > &ft)
void cntr::herm_matrix_timestep_moving< T >::left_multiply_hermconj(function_moving< T > &ft)
std::complex< T > * cntr::herm_matrix_timestep_moving< T >::lesptr(int deltj)
Pointer to lesser component at a given time, representing G^<(t0,t0-deltj).
void cntr::herm_matrix_timestep_moving< T >::MPI_Reduce(int root)
Performs MPI reduction.
herm_matrix_timestep_moving & cntr::herm_matrix_timestep_moving< T >::operator=(const herm_matrix_timestep_moving &g)
References cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving.
void cntr::herm_matrix_timestep_moving< T >::print_to_file(const char *file, int precision=16)
void cntr::herm_matrix_timestep_moving< T >::read_from_file(const char *file)
void cntr::herm_matrix_timestep_moving< T >::read_from_hdf5(const char *filename, const char *groupname)
Reads data from an HDF5 file with a specified filename and group name.
void cntr::herm_matrix_timestep_moving< T >::read_from_hdf5(hid_t group_id)
Reads data from an HDF5 file for the specified group ID.
void cntr::herm_matrix_timestep_moving< T >::read_from_hdf5(hid_t group_id, const char *groupname)
void cntr::herm_matrix_timestep_moving< T >::resize(int tc, int size1)
References cntr::herm_matrix_timestep_moving< T >::size1, cntr::herm_matrix_timestep_moving< T >::tc.
std::complex< T > * cntr::herm_matrix_timestep_moving< T >::retptr(int deltj)
Pointer to retarded component at a given time, representing G^R(t0,t0-deltj).
void cntr::herm_matrix_timestep_moving< T >::right_multiply(function_moving< T > &ft)
void cntr::herm_matrix_timestep_moving< T >::right_multiply_hermconj(function_moving< T > &ft)
void cntr::herm_matrix_timestep_moving< T >::set_les(int deltj, cplx x)
void cntr::herm_matrix_timestep_moving< T >::set_les(int deltj, Matrix &M)
void cntr::herm_matrix_timestep_moving< T >::set_matrixelement(int i1, int i2, herm_matrix_moving< T > &G, int delti_g, int j1, int j2)
void cntr::herm_matrix_timestep_moving< T >::set_matrixelement(int i1, int i2, herm_matrix_timestep_moving< T > &G, int j1, int j2)
References cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving.
void cntr::herm_matrix_timestep_moving< T >::set_matrixelement(int i1, int i2, herm_matrix_timestep_moving_view< T > &G, int j1, int j2)
void cntr::herm_matrix_timestep_moving< T >::set_ret(int deltj, cplx x)
void cntr::herm_matrix_timestep_moving< T >::set_ret(int deltj, Matrix &M)
void cntr::herm_matrix_timestep_moving< T >::set_timestep(herm_matrix< T > &G, herm_matrix< T > &Gcc, int tstp_g)
void cntr::herm_matrix_timestep_moving< T >::set_timestep(herm_matrix_moving< T > &g1, int delti_g)
void cntr::herm_matrix_timestep_moving< T >::set_timestep(herm_matrix_timestep< T > &G, herm_matrix_timestep< T > &Gcc)
void cntr::herm_matrix_timestep_moving< T >::set_timestep(herm_matrix_timestep_moving< T > &g1)
References cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving.
void cntr::herm_matrix_timestep_moving< T >::set_timestep(herm_matrix_timestep_moving_view< T > &g1)
void cntr::herm_matrix_timestep_moving< T >::set_timestep(herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
void cntr::herm_matrix_timestep_moving< T >::set_timestep_zero(void)
Clears the stored timestep data. (set to zero).
int cntr::herm_matrix_timestep_moving< T >::sig(void) const
Returns the statistical sign (Bose = +1, Fermi = -1).
Referenced by cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving.
int cntr::herm_matrix_timestep_moving< T >::size1(void) const
Returns the number of columns.
Referenced by cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving, cntr::herm_matrix_timestep_moving< T >::resize.
int cntr::herm_matrix_timestep_moving< T >::size2(void) const
Returns the number of rows (CurrentlyL always the same as number of columns!).
void cntr::herm_matrix_timestep_moving< T >::smul(cplx alpha)
void cntr::herm_matrix_timestep_moving< T >::smul(T alpha)
Scales the stored values by a scalar.
int cntr::herm_matrix_timestep_moving< T >::tc(void) const
Returns the time cut-off.
Referenced by cntr::herm_matrix_timestep_moving< T >::herm_matrix_timestep_moving, cntr::herm_matrix_timestep_moving< T >::resize.
void cntr::herm_matrix_timestep_moving< T >::write_to_hdf5(const char *filename, const char *groupname, h5_mode mode=h5_mode::create_truncate)
Writes data to an HDF5 file with a specified filename and group name.
void cntr::herm_matrix_timestep_moving< T >::write_to_hdf5(hid_t group_id)
Writes data to an HDF5 file for the specified group ID.
void cntr::herm_matrix_timestep_moving< T >::write_to_hdf5(hid_t group_id, const char *groupname)
cntr::herm_matrix_timestep_moving< T >::~herm_matrix_timestep_moving()