cntr_getset_herm_matrix_timestep_view_inc.hpp
void get_gtr(const int i, const int j, cdmatrix &G_gtr, herm_matrix_timestep_view< T > &G)
Returns the greater component of a hermitian contour function at given times.
Purpose Returns the greater component $ G^>(t_i,t_j) $ at given times $ t_i$ and $ t_j$ from $G^<(t_i,t_j)$ and $G^\mathrm{R}(t_i,t_j)$. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_gtr [cdmatrix] The greater component (returned to an eigen3 matrix). G [herm_matrix_timestep_view] Contour function G
References get_gtr.
void get_gtr(const int i, const int j, cdmatrix &G_gtr, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the greater component of a general contour function at given times.
Purpose Returns the greater component $ G^>(t_i,t_j) $ at given times $ t_i$ and $ t_j$ from $G^<(t_i,t_j)$ and $G^\mathrm{R}(t_i,t_j)$. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_gtr [cdmatrix] The greater component (returned to an eigen3 matrix). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
References get_les, get_ret.
void get_gtr(const int i, const int j, std::complex< T > &G_gtr, herm_matrix_timestep_view< T > &G)
Returns the greater component of a hermitian contour function at given times.
Purpose Returns the greater component $ G^>(t_i,t_j) $ at given times $ t_i$ and $ t_j$ from $G^<(t_i,t_j)$ and $G^\mathrm{R}(t_i,t_j)$. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_gtr [complex<T>] The greater component (scalar GF). G [herm_matrix_timestep_view] Contour function G
References get_gtr.
void get_gtr(const int i, const int j, std::complex< T > &G_gtr, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the greater component of a general contour function at given times.
Purpose Returns the greater component $ G^>(t_i,t_j) $ at given times $ t_i$ and $ t_j$ from $G^<(t_i,t_j)$ and $G^\mathrm{R}(t_i,t_j)$. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_gtr [complex<T>] The greater component (scalar GF). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
References get_les, get_ret.
Referenced by get_gtr, get_gtr.
void get_les(const int i, const int j, cdmatrix &G_les, herm_matrix_timestep_view< T > &G)
Returns the lesser component of a hermitian contour function at given times.
Purpose Returns the lesser component $ G^<(t_i,t_j) $ at given times $ t_i$ and $ t_j$. For $ i > j$ the hermitian symmetry is assumed. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_les [cdmatrix] The lesser component (returned to an eigen3 matrix). G [herm_matrix_timestep_view] Contour function G
References get_les.
void get_les(const int i, const int j, cdmatrix &G_les, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the lesser component of a general contour function at given times.
Purpose Returns the lesser component $ G^<(t_i,t_j) $ at given times $ t_i$ and $ t_j$. For $ i > j$ the hermitian conjugate $G^\ddagger$ is used. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_les [cdmatrix] The lesser component (returned to an eigen3 matrix). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
void get_les(const int i, const int j, std::complex< T > &G_les, herm_matrix_timestep_view< T > &G)
Returns the lesser component of a hermitian contour function at given times.
Purpose Returns the lesser component $ G^<(t_i,t_j) $ at given times $ t_i$ and $ t_j$. For $ i > j$ the hermitian symmetry is assumed. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_les [complex<T>] The lesser component (scalar GF). G [herm_matrix_timestep_view] Contour function G
References get_les.
void get_les(const int i, const int j, std::complex< T > &G_les, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the lesser component of a general contour function at given times.
Purpose Returns the lesser component $ G^<(t_i,t_j) $ at given times $ t_i$ and $ t_j$. For $ i > j$ the hermitian conjugate $G^\ddagger$ is used. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_les [complex<T>] The lesser component (scalar GF). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
Referenced by get_gtr, get_gtr, get_les, get_les.
void get_mat(const int m, cdmatrix &G_mat, herm_matrix_timestep_view< T > &G)
Returns the Matsubara component of a general contour function at given times.
Purpose Returns the lesser component $ G^\mathrm{M}(\tau_m) $ at given imaginary time $ \tau_m$. m [int] Index of time $ \tau_m$ . G_mat [complex<T>] The Matsubara component (scalar GF). G [herm_matrix_timestep_view] Contour function G
void get_mat(const int m, cdmatrix &G_mat, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the Matsubara component of a general contour function at given times.
Purpose Returns the lesser component $ G^\mathrm{M}(\tau_m) $ at given imaginary time $ \tau_m$. m [int] Index of time $ \tau_m$ . G_mat [complex<T>] The Matsubara component (scalar GF). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
void get_mat(const int m, std::complex< T > &G_mat, herm_matrix_timestep_view< T > &G)
Returns the Matsubara component of a general contour function at given times.
Purpose Returns the lesser component $ G^\mathrm{M}(\tau_m) $ at given imaginary time $ \tau_m$. m [int] Index of time $ \tau_m$ . G_mat [complex<T>] The Matsubara component (scalar GF). G [herm_matrix_timestep_view] Contour function G
void get_mat(const int m, std::complex< T > &G_mat, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the Matsubara component of a general contour function at given times.
Purpose Returns the lesser component $ G^\mathrm{M}(\tau_m) $ at given imaginary time $ \tau_m$. m [int] Index of time $ \tau_m$ . G_mat [complex<T>] The Matsubara component (scalar GF). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
void get_ret(const int i, const int j, cdmatrix &G_ret, herm_matrix_timestep_view< T > &G)
Returns the retarded component of a hermitian contour function at given times.
Purpose Returns the retarded component $ G^\mathrm{R}(t_i,t_j) $ at given times $ t_i$ and $ t_j$. We assume $G^\mathrm{R}(t_i,t_j)$ can be analytically continued to $ j > i$, for which the hermitian conjugate $G^\ddagger$ is used. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_ret [cdmatrix] The retarded component (returned to an eigen3 matrix). G [herm_matrix_timestep_view] Contour function G
References get_ret.
void get_ret(const int i, const int j, cdmatrix &G_ret, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the retarded component of a general contour function at given times.
Purpose Returns the retarded component $ G^\mathrm{R}(t_i,t_j) $ at given times $ t_i$ and $ t_j$. We assume $G^\mathrm{R}(t_i,t_j)$ can be analytically continued to $ j > i$, for which the hermitian conjugate $G^\ddagger$ is used. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_ret [cdmatrix] The retarded component (returned to an eigen3 matrix). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
void get_ret(const int i, const int j, std::complex< T > &G_ret, herm_matrix_timestep_view< T > &G)
Returns the retarded component of a hermitian contour function at given times.
Purpose Returns the retarded component $ G^\mathrm{R}(t_i,t_j) $ at given times $ t_i$ and $ t_j$. We assume $G^\mathrm{R}(t_i,t_j)$ can be analytically continued to $ j > i$, for which the hermitian conjugate $G^\ddagger$ is used. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_ret [complex<T>] The retarded component (scalar GF). G [herm_matrix_timestep_view] Contour function G
References get_ret.
void get_ret(const int i, const int j, std::complex< T > &G_ret, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the retarded component of a general contour function at given times.
Purpose Returns the retarded component $ G^\mathrm{R}(t_i,t_j) $ at given times $ t_i$ and $ t_j$. We assume $G^\mathrm{R}(t_i,t_j)$ can be analytically continued to $ j > i$, for which the hermitian conjugate $G^\ddagger$ is used. i [int] Index of time $ t_i$ . j [int] Index of time $ t_j$ . G_ret [complex<T>] The retarded component (scalar GF). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
Referenced by get_gtr, get_gtr, get_ret, get_ret.
void get_tv(const int i, const int m, cdmatrix &G_tv, herm_matrix_timestep_view< T > &G)
Returns the left-mixing component of a hermitian contour function at given times.
Purpose Returns the left-mixing component $ G^\rceil(t_i,\tau_m) $ at given times $ t_i$ and $ \tau_m$. i [int] Index of time $ t_i$ . m [int] Index of time $ \tau_m$ . G_tv [cdmatrix] The left-mixing component (returned to an eigen3 matrix). G [herm_matrix_timestep_view] Contour function G
References get_tv.
void get_tv(const int i, const int m, cdmatrix &G_tv, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the left-mixing component of a general contour function at given times.
Purpose Returns the left-mixing component $ G^\rceil(t_i,\tau_m) $ at given times $ t_i$ and $ \tau_m$. i [int] Index of time $ t_i$ . m [int] Index of time $ \tau_m$ . G_tv [cdmatrix] The left-mixing component (returned to an eigen3 matrix). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
void get_tv(const int i, const int m, std::complex< T > &G_tv, herm_matrix_timestep_view< T > &G)
Returns the left-mixing component of a hermitian contour function at given times.
Purpose Returns the left-mixing component $ G^\rceil(t_i,\tau_m) $ at given times $ t_i$ and $ \tau_m$. i [int] Index of time $ t_i$ . m [int] Index of time $ \tau_m$ . G_tv [complex<T>] The left-mixing component (scalar GF). G [herm_matrix_timestep_view] Contour function G
References get_tv.
void get_tv(const int i, const int m, std::complex< T > &G_tv, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the left-mixing component of a general contour function at given times.
Purpose Returns the left-mixing component $ G^\rceil(t_i,\tau_m) $ at given times $ t_i$ and $ \tau_m$. i [int] Index of time $ t_i$ . m [int] Index of time $ \tau_m$ . G_tv [complex<T>] The left-mixing component (scalar GF). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
Referenced by get_tv, get_tv.
void get_vt(const int m, const int i, cdmatrix &G_vt, herm_matrix_timestep_view< T > &G)
Returns the right-mixing component of a hermitian contour function at given times.
Purpose Returns the right-mixing component $ G^\lceil(\tau_m,t_i) $ at given times $ t_i$ and $ \tau_m$ assuming hermitian symmetry. m [int] Index of time $ \tau_m$ . i [int] Index of time $ t_i$ . G_vt [cdmatrix] The right-mixing component (returned to an eigen3 matrix). G [herm_matrix_timestep] Contour function G
References get_vt.
void get_vt(const int m, const int i, cdmatrix &G_vt, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the right-mixing component of a general contour function at given times.
Purpose Returns the right-mixing component $ G^\lceil(\tau_m,t_i) $ at given times $ t_i$ and $ \tau_m$. The hermitian conjugate $G^\ddagger$ is used. m [int] Index of time $ \tau_m$ . i [int] Index of time $ t_i$ . G_vt [cdmatrix] The right-mixing component (returned to an eigen3 matrix). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
void get_vt(const int m, const int i, std::complex< T > &G_vt, herm_matrix_timestep_view< T > &G)
Returns the right-mixing component of a hermitian contour function at given times.
Purpose Returns the right-mixing component $ G^\lceil(\tau_m,t_i) $ at given times $ t_i$ and $ \tau_m$ assuming hermitian symmetry. m [int] Index of time $ \tau_m$ . i [int] Index of time $ t_i$ . G_vt [complex<T>] The right-mixing component (scalar GF). G [herm_matrix_timestep_view] Contour function G
References get_vt.
void get_vt(const int m, const int i, std::complex< T > &G_vt, herm_matrix_timestep_view< T > &G, herm_matrix_timestep_view< T > &Gcc)
Returns the right-mixing component of a general contour function at given times.
Purpose Returns the right-mixing component $ G^\lceil(\tau_m,t_i) $ at given times $ t_i$ and $ \tau_m$. The hermitian conjugate $G^\ddagger$ is used. m [int] Index of time $ \tau_m$ . i [int] Index of time $ t_i$ . G_vt [complex<T>] The right-mixing component (scalar GF). G [herm_matrix_timestep_view] Contour function G Gcc [herm_matrix_timestep_view] Hermitian conjugate $G^\ddagger$ of $G$.
Referenced by get_vt, get_vt.