fourier
typedef std::complex<double> fourier::cplx
void fourier::complex_dftcor_cubic(double w, double delta, double a, double b, cplx *endpts, cplx *endcor, double *corfac)
Returns correction factor $W(\theta)$ and evaluate boundary correction terms needed for cubically corrected DFT.
Purpose For a function $f(t)$, represented on an equidistant grid $t_n= n h$, $n=0,\dots,N$, we would like to compute the Fourier integral $I(\omega) = \int^b_a dt\, e^{i \omega t}f(t)$. Using piecewie cubic interpolation of $f(t)$, the $I(\omega)$ can be computed by by cubically corrected discrete Fourier transformation (DFT). The algorithm is explained in W. H. Press, S. A. Teukolosky, W. T. Vetterling, B. P. Flannery, Numerical Recipes 3rd Edition: The Art of Scientific Computing, Cambridge University Press, 2007, chapter 13.9 complex_dftcor_cubic computes the required correction factor $W(\theta)$ and the boundary terms $\alpha_j(\theta)f_j$, $j=0,\dots,3$, and $ e^{i\omega(b-a)}\alpha^*_j(\theta)f_{N-j} $ where $\theta = \omega h$. w [double] frequency $\omega$ delta [double] grid spacing $h$ a [double] starting point of interval b [double] end point of interval endpts [complex] 'endpts[j]', 'j=0,1,2,3', corresponds to $f_j$, while 'endpts[7-j]', 'j=0,1,2,3', corresponds to $f_{N-j}$ endcor [complex] on return, boundary correction terms, stored in the order as 'endpts' corfac [double] on return, correction factor $W(\theta)$
Referenced by dft_cplx.
void fourier::dft_cplx(double w, int n, double a, double b, cplx *f, cplx &res, cplx &err)
Computes the Fourier integral $I(\omega) = \int^b_a dt\, e^{i \omega t}f(t)$ using cubically corrected DFT.
Purpose For a function $f(t)$, represented on an equidistant grid $t_j= j h$, $j=0,\dots,n$, we would like to compute the Fourier integral $I(\omega) = \int^b_a dt\, e^{i \omega t}f(t)$. Using piecewie cubic interpolation of $f(t)$, the $I(\omega)$ can be computed by by cubically corrected discrete Fourier transformation (DFT). The algorithm is explained in W. H. Press, S. A. Teukolosky, W. T. Vetterling, B. P. Flannery, Numerical Recipes 3rd Edition: The Art of Scientific Computing, Cambridge University Press, 2007, chapter 13.9 dft_cplx computes the integral $I(\omega)$, using the cubic correction factor and boundary correction terms computed by complex_dftcor_cubic. Furthermore, an approximate error is returned, given the difference using n and (n+1)/2 points. w [double] frequency $\omega$ n [int] number of time points $t_j=j h, j=0,\dots,n$ a [double] starting point of interval b [double] end point of interval f [complex] pointer containing the function values res [complex] Fourier integral $I(\omega)$ err [complex] difference using 'n' and '(N+1)/2' points.
References complex_dftcor_cubic.
Referenced by fourier::adft_func::dft, fourier::adft_func::sample.
void fourier::get_dftcorr_cubic(double th, double *corfac, cplx *endcor)
Returns correction factor $W(\theta)$ and boundary correction terms $\alpha_j(\theta)$ needed for cubically corrected DFT.
Purpose For a function $f(t)$, represented on an equidistant grid $t_n= n h$, $n=0,\dots,N$, we would like to compute the Fourier integral $I(\omega) = \int^b_a dt\, e^{i \omega t}f(t)$. Using piecewie cubic interpolation of $f(t)$, the $I(\omega)$ can be computed by by cubically corrected discrete Fourier transformation (DFT). The algorithm is explained in W. H. Press, S. A. Teukolosky, W. T. Vetterling, B. P. Flannery, Numerical Recipes 3rd Edition: The Art of Scientific Computing, Cambridge University Press, 2007, chapter 13.9 get_dftcorr_cubic computes the required correction factor $W(\theta)$ and the boundary terms $\alpha_i(\theta)$, $i=0,\dots,3$, where $\theta = \omega h$. th [double] $\theta = \omega h$ as explained above. corfac [double] on return, correction factor $W(\theta)$ endcor [complex] on return, boundary term $\alpha_j(\theta)$, stored in 'endcor[j]'
void fourier::get_dftcorr_linear(double th, double *corfac, cplx *endcor)
Returns correction factor $W(\theta)$ and boundary correction term $\alpha_0(\theta)$ needed for linearly corrected DFT.
Purpose For a function $f(t)$, represented on an equidistant grid $t_n= n h$, $n=0,\dots,N$, we would like to compute the Fourier integral $I(\omega) = \int^b_a dt\, e^{i \omega t}f(t)$. Using linear interpolation of $f(t)$, the $I(\omega)$ can be computed by by linearlt corrected discrete Fourier transformation (DFT). The algorithm is explained in W. H. Press, S. A. Teukolosky, W. T. Vetterling, B. P. Flannery, Numerical Recipes 3rd Edition: The Art of Scientific Computing, Cambridge University Press, 2007, chapter 13.9 get_dftcorr_linear computes the required correction factor $W(\theta)$ and the boundary term $\alpha_0(\theta)$, where $\theta = \omega h$. th [double] $\theta = \omega h$ as explained above. corfac [double] on return, correction factor $W(\theta)$ endcor [complex] on return, boundary term $\alpha_0(\theta)$