linalg
void linalg::cplx_matrix_inverse(void *a, void *x, int n)
Evaluate the inverse matrix of a complex matrix $a$.
Purpose Evaluate the inverse matrix of a given complex matrix $a$ and put it to $x$. a A complex square matrix given as a pointer. x A complex square matrix into which $a^{-1}$ is set. Given as a pointer. n Size of the matrix $a$ and $x$.
References get_cdmatrix, set_cdmatrix.
void linalg::cplx_sq_solve(void *a, void *b, void *x, int dim)
Solve a linear equation ax=b.
Purpose Solve a linear equation ax=b for a given complex square matrix $a$ and a complex vector $b$. a A complex square matrix given as a pointer b A complex vector given as a pointer x A complex vector into which the solution is set. dim Size of the matrix and the vector
References get_cdvector, set_cdmatrix, set_cdvector.
void linalg::cplx_sq_solve_many(void *a, void *b, void *x, int dim, int d)
Solve a linear equation $ {\rm Diag}[a,a,a,.,a] x=b $.
Purpose Solve a linear equation $ {\rm Diag}[a,a,a,.,a] x=b $ for a given complex square matrix $a$ and a complex vector $b$. The size of $a$ is $n$. Here $ {\rm Diag}[a,a,a,.,a]$ is the block diagonal square matrix, whose size is ${\rm dim}\times d$. a A complex square matrix, whose size is ${\rm dim}$. b A complex vector, whose size is $n\times d$ x A complex vector into which the solution is set. dim Size of the matrix $a$ d ${\rm dim}\times d$ is the size of $b$ and $x$.
References get_cdvector, set_cdmatrix, set_cdvector.
void linalg::eigen_hermv(int size, std::complex< double > *A, double *eval, std::complex< double > *evec)
Evaluate the eigen set of a given Hermitian matrix $A$.
Purpose Evaluate the eigen system of a given Hermitian matrix $A$, and put the eigen values into "eval" and and the eigen vectors into "evec". size Size of the matrix $A$. A A Hermitian matrix given as a pointer. eval A complex vector into which the eigen values are set. Given as a pointer. evec A complex Matrix into which the eigen vectors are set. Given as a pointer.
References get_cdmatrix, get_dvector, set_cdmatrix.
void linalg::get_cdmatrix(int n, void *a, cdmatrix &A)
Referenced by cplx_matrix_inverse, eigen_hermv.
void linalg::get_cdvector(int n, void *a, cdvector &A)
Referenced by cplx_sq_solve, cplx_sq_solve_many.
void linalg::get_dmatrix(int n, void *a, const dmatrix &A)
Referenced by linalg_matrix_inverse.
void linalg::get_dvector(int n, void *a, dvector &A)
Referenced by eigen_hermv, real_sq_solve.
void linalg::linalg_matrix_inverse(double *a, double *x, int n)
Evaluate the inverse matrix of a real matrix $a$.
Purpose Evaluate the inverse matrix of a given real matrix $a$ and put it to $x$. a A real square matrix given as a pointer. x A real square matrix into which $a^{-1}$ is set. Given as a pointer. n Size of the matrix $a$ and $x$.
References get_dmatrix, set_dmatrix.
void linalg::real_sq_solve(double *ad, double *bd, double *xd, int dim)
Solve a linear equation ax=b.
Purpose Solve a linear equation ax=b for a given real square matrx ( $a$) and a real vector ( $b$). ad A real square matrix given as a pointer. bd A real vector given as a pointer. xd A real vector into which the solution is set. Given as a pointer. dim Size of the matrix and the vector
References get_dvector, set_dmatrix, set_dvector.
void linalg::set_cdmatrix(int n, void *a, cdmatrix &A)
Referenced by cplx_matrix_inverse, cplx_sq_solve, cplx_sq_solve_many, eigen_hermv.
void linalg::set_cdvector(int n, void *a, cdvector &A)
Referenced by cplx_sq_solve, cplx_sq_solve_many.
void linalg::set_dmatrix(int n, void *a, dmatrix &A)
Referenced by linalg_matrix_inverse, real_sq_solve.
void linalg::set_dvector(int n, void *a, dvector &A)
Referenced by real_sq_solve.