ness2
dyson_bath_type
fft_domain
fft_integral_method
typedef std::complex<double> ness2::cdouble
typedef std::complex<double> ness2::cplx
Define complex data type ... same as in cntr::
void ness2::Bubble1_ness(herm_matrix_ness &C, herm_matrix_ness &A, herm_matrix_ness &B)
void ness2::Bubble1_ness(herm_matrix_ness &C, int c1, int c2, herm_matrix_ness &A, int a1, int a2, herm_matrix_ness &B, int b1, int b2)
Calculate the bubble diagram of first type: $ C_{c_1,c_2} (t)= i A_{a_1,a_2} (t) B_{b_2,b_1} (-t) $
Purpose Evaluate Green's function C given by the bubble diagram equation $ C_{c_1,c_2} (t)= i A_{a_1,a_2} (t) B_{b_2,b_1} (-t) $. The evaluation is done for all time points and for the lesser and retarded component. &C Green's function to store result in &c1 First orbital index of C &c2 Second orbital index of C &A Time Green's function &a1 First orbital index of A &a2 Second orbital index of A &B Time Green's function &b1 First orbital index of B &b2 Second orbital index of B
void ness2::Bubble2_ness(herm_matrix_ness &C, herm_matrix_ness &A, herm_matrix_ness &B)
void ness2::Bubble2_ness(herm_matrix_ness &C, int c1, int c2, herm_matrix_ness &A, int a1, int a2, herm_matrix_ness &B, int b1, int b2)
Calculate the bubble diagram of second type: $ C_{c_1,c_2} (t)= i A_{a_1,a_2} (t) B_{b_1,b_2} (t) $
Purpose Evaluate Green's function C given by the bubble diagram equation $ C_{c_1,c_2} (t)= i A_{a_1,a_2} (t) B_{b_1,b_2} (t) $. The evaluation is done for all time points and for the lesser ad retarded component. &C Time Green's function to store result in &c1 First orbital index of C &c2 Second orbital index of C &A Time Green's function &a1 First orbital index of A &a2 Second orbital index of A &B Time Green's function &b1 First orbital index of B &b2 Second orbital index of B
void ness2::cntr2ness(herm_matrix_ness &Gness, cntr::herm_matrix< T > &Gcntr, int tstp=-1)
Convert CNTR Green's function cntr::herm_matrix to NESS ness2::herm_matrix_ness by sampling a given time slice.
Read $ G_{\rm ness}^{R|<}(t) = G{\rm cntr}^{R|<}(tstp, tstp - t) $ from CNTR object at time slice tstp, and write to NESS object. Values at negative times $ t < 0 $ are set by Hermitian symmetry: $ G^<(-t) = -[G^<(t)]^\dagger $ If tstp is smaller than the maximum time in Gness, the tail is left zero. GcntrType Type of the contour Green's function (cntr::herm_matrix,cntr::herm_matrix_timestep, cntr::herm_matrix_moving, cntr::herm_matrix_timestep_moving) Gness Target steady-state Green's function (time domain filled) Gcntr Source two-time Green's function tstp Time slice in Gcntr to sample from (defaults to max time) std::runtime_error If dimensions mismatch
References ness2::herm_matrix_ness::Nft_, cntr::herm_matrix< T >::nt, ness2::herm_matrix_ness::set_les, ness2::herm_matrix_ness::set_ret, ness2::herm_matrix_ness::set_zero, cntr::herm_matrix< T >::size1, ness2::herm_matrix_ness::size1_, time.
Referenced by cntr2ness, cntr2ness.
void ness2::cntr2ness(herm_matrix_ness &Gness, cntr::herm_matrix_moving< T > &Gcntr, int tstp=-1)
References cntr2ness.
void ness2::cntr2ness(herm_matrix_ness &Gness, cntr::herm_matrix_timestep< T > &Gcntr, int tstp=-1)
References ness2::herm_matrix_ness::Nft_, ness2::herm_matrix_ness::set_les, ness2::herm_matrix_ness::set_ret, ness2::herm_matrix_ness::set_zero, cntr::herm_matrix_timestep< T >::size1, ness2::herm_matrix_ness::size1_, time, cntr::herm_matrix_timestep< T >::tstp.
void ness2::cntr2ness(herm_matrix_ness &Gness, cntr::herm_matrix_timestep_moving< T > &Gcntr, int tstp=-1)
References cntr2ness.
void ness2::cntr2ness(herm_matrix_ness &Gness, cntr::herm_matrix_timestep_moving_view< T > &Gcntr, int tstp=-1)
References cntr::herm_matrix_timestep_moving_view< T >::get_les, cntr::herm_matrix_timestep_moving_view< T >::get_ret, ness2::herm_matrix_ness::Nft_, ness2::herm_matrix_ness::set_les, ness2::herm_matrix_ness::set_ret, ness2::herm_matrix_ness::set_zero, cntr::herm_matrix_timestep_moving_view< T >::size1, ness2::herm_matrix_ness::size1_, cntr::herm_matrix_timestep_moving_view< T >::tc, time.
void ness2::compute_lesser(fft_array &G, int nt, Integrand &integrand, double lo, double hi, double h, int nn, int limit)
References fourier::adft_func::dft, ness2::fft_array::Nft_, fourier::adft_func::sample, ness2::fft_array::set_element, ness2::fft_array::set_zero, ness2::fft_array::size1_, time.
Referenced by green_equilibrium_ness_bose, green_equilibrium_ness_fermi.
void ness2::convolution_density_matrix(cdmatrix &result, int bosefermi, herm_matrix_ness &A, herm_matrix_ness &B, double h)
Compute the equal-time lesser component of the product $ i (A \cdot B)^< $ for two steady-state Green's functions in NESS representation.
This routine evaluates \[ M = bosefermi* i (A \cdot B)^<(t=0) = bosefermi*i \, \mathcal{F}^{-1} \left[ A^<(\omega) B^A(\omega) + A^R(\omega) B^<(\omega) \right]_{t=0} \] The function transforms A and B to frequency (overwriing eisting values) on the frequency grid of the NESS object, limited to the range result Complex matrix of dimension (size1 x size1) containing the equal-time value $ i(A \cdot B)^<(t=0) $. bosefermi (+1) for bosonic functions, (-1) for fermionic functions h Time step used for the Fourier transforms. A First steady-state Green's function (herm_matrix_ness) B Second steady-state Green's function (herm_matrix_ness)
void ness2::density_matrix(cdmatrix &result, int bosefermi, herm_matrix_ness &A)
Compute the equal-time density matrix from the lesser component of a NESS Green's function.
This routine evaluates \[ \rho = {\tt bosefermi} \cdot i \, A^<(t=0) \] where $ A^<(t) $ is the lesser Green's function in the time domain, and $t=0$ denotes the equal-time value. result Complex matrix of dimension (size1 x size1) containing $ {\tt bosefermi} \cdot i A^<(t=0) $. bosefermi (+1) for bosonic functions, (-1) for fermionic functions A Steady-state Green's function (herm_matrix_ness) in the time domain.
double ness2::distance_norm2(fft_array &A, fft_array &B, fft_domain type)
Compute Euclidean distance between two fft_array objects in time or frequency domain
Purpose Computes the L2 norm (Euclidean distance) $ \|A - B\|_2 = \sqrt{ \sum_i |A_i - B_i|^2 } $ between two fft_array objects in either time or frequency domain. &A First fft_array object &B Second fft_array object type fft_domain::time or fft_domain::freq – determines which internal data to compare Euclidean norm of the difference std::invalid_argument If array sizes or shapes do not match
double ness2::distance_norm2(herm_matrix_ness &A, herm_matrix_ness &B, fft_domain type)
Compute Euclidean distance between two herm_matrix_ness objects
Purpose Computes the combined L2 norm for retarded and lesser components: $ \|A - B\|_2 = \sqrt{ \|A^{ret} - B^{ret}\|_2^2 + \|A^{les} - B^{les}\|_2^2 } $ &A First herm_matrix_ness object &B Second herm_matrix_ness object type fft_domain::time or fft_domain::freq – domain to compare Total Euclidean norm of the difference across components
fft_array ness2::downsample(fft_array &in, int factor)
Downsampling of a fft_array to a coarser time grid, taking only every factor entry of the original object.
The new length is $ N_{ft1} = \frac{N_{ft}}{\tt factor} $. In frequency space, only values $ 0, \ldots, \frac{N_{ft1}}{2} - 1, N_{ft} - \frac{N_{ft1}}{2}, \ldots, N_{ft} - 1 $ of the input are written to the output object. Returns a downsampled fft_array object. It is required that $ N_{ft} $ is an integer multiple of factor, and $ N_{ft1} $ (the new length) is still an integer multiple of 2. in Input array (fft_array). factor Coarse-graining factor, larger than one.
herm_matrix_ness ness2::downsample(herm_matrix_ness &in, int factor)
Downsampling of a herm_matrix_ness to a coarser time grid, taking only every factor entry of the original object.
The new length is $ N_{ft1} = \frac{N_{ft}}{\tt factor} $. In frequency space, only values $ 0, \ldots, \frac{N_{ft1}}{2} - 1, N_{ft} - \frac{N_{ft1}}{2}, \ldots, N_{ft} - 1 $ of the input are written to the output object. Returns a downsampled herm_matrix_ness object. It is required that $ N_{ft} $ is an integer multiple of factor, and $ N_{ft1} $ (the new length) is still an integer multiple of 2. in Input steady-state Green's function (herm_matrix_ness). factor Coarse-graining factor, larger than one.
void ness2::dyson(herm_matrix_ness &G, double mu, cdmatrix &epsilon, herm_matrix_ness &Sigma, double h, fft_integral_method method=FFT_TRAPEZ, dyson_bath_type bath_type=BATH_NONE, double bath_eta=0, double bath_beta=0, double bath_mu=0)
Solve the Dyson equation for the steady-state Green's function.
PurposeComputes the time-domain solution $ G^{R|<}(t) $ of the Dyson equation for a steady-state system, using a frequency-domain method with optional bath regularization. The method transforms $ \Sigma^{R|<}(t) $ to frequency space, solves Dyson equations there, and back-transforms to obtain $ G^{R|<}(t) $. G Output Green's function $ G^{R|<}(t) $ of type herm_matrix_ness, modified in-place. mu Chemical potential $ \mu $. epsilon Complex-valued single-particle Hamiltonian matrix $ \epsilon $ (dimension must match G). Sigma Input self-energy $ \Sigma^{R|<}(t) $ of type herm_matrix_ness, defined on the same grid as G. h Time step size $ h $ used for time grids. method Integral transformation method (default = FFT_TRAPEZ). Currently only FFT_TRAPEZ is implemented. bath_type Type of bath regularization added to the self-energy. If bath_type != REG_NONE, a bath self-energy $ \Sigma_{\rm reg} $ is added to $ \Sigma $: REG_CONST: Constant density (Lorentzian broadening) REG_GAUSS: Gaussian cutoff in frequency space. REG_OHMIC: Ohmic spectral function with cutoff. bath_eta Broadening parameter $ \eta $ for the bath (used for all regularization types except BATH_NONE). bath_beta Inverse temperature $ \beta $ of the bath (used in BATH_CONST, BATH_GAUSS, BATH_OHMIC). bath_mu Chemical potential $ \mu_{\rm bath} $ of the bath (used in BATH_CONST, BATH_GAUSS).
References BATH_NONE, FFT_TRAPEZ.
void ness2::dyson_fft(herm_matrix_ness &G, herm_matrix_ness &Sigma, cdmatrix &H, double mu, double h, dyson_bath_type bath_type, double bath_eta, double bath_beta, double bath_mu)
void ness2::green_equilibrium_ness(int bosefermi, herm_matrix_ness &G, DOS &dos, double beta, double mu, double h, fft_integral_method method, int limit=100, int nn=20)
Equilibrium steady-state Green's function systems
Constructs a retarded and lesser Green's function in the time domain for a system in thermal equilibrium, using a specified density of states and numerical Fourier integration method. DOS A density of states class providing: double lo_ — lower frequency bound double hi_ — upper frequency bound double operator()(double omega) — density of states $ A(\omega) $ bose_fermi = BOSON (+1) or FERMION (-1) sign G Output: Green's function object (herm_matrix_ness) to be filled in time domain dos Density of states object used to define the spectral function beta Inverse temperature $ \beta $ h Time step size mu Chemical potential $ \mu $ method Integration method to use for the Fourier transform. One of: FFT_TRAPEZ: Simple piecewise-constant quadrature (trapezoidal rule) FFT_ADAPTIVE: Adaptive quadrature as in libcntr (uses nn and limit) nn Number of sub-sample points per interval (used only if method == FFT_ADAPTIVE) limit Maximum number of intervals in adaptive Fourier transform (used only if method == FFT_ADAPTIVE) Computes the time-domain Green's functions: \[G^R(t) = -i \int_{\mathrm{lo}}^{\mathrm{hi}} d\omega\, A(\omega) e^{-i \omega t} \] \[G^<(t) = - \xi i \int_{\mathrm{lo}}^{\mathrm{hi}} d\omega\, A(\omega) f_F(\omega - \mu) e^{-i \omega t}, \quad f_F(x) = \frac{1}{e^{\beta x} - \xi} \] where $\xi$ = BOSE or FERMI, and $ A(\omega)$ is computed from the density of states. The integration bounds are taken from dos.lo_ to dos.hi_. For FFT_ADAPTIVE, a frequency-adaptive scheme is used, refining the interval until convergence. For FFT_TRAPEZ the FFT grid defined by Nft_ and h is used, nn and limit are ignored
References green_equilibrium_ness_bose, green_equilibrium_ness_fermi.
void ness2::green_equilibrium_ness_bose(herm_matrix_ness &G, DOS &dos, double beta, double mu, double h, fft_integral_method method, int limit, int nn)
References compute_lesser, FFT_ADAPTIVE, FFT_TRAPEZ, freq, ness2::grid_info::freq_at, green_equilibrium_ret_ness_adaptive, ness2::herm_matrix_ness::integral_transform_to_time, ness2::herm_matrix_ness::les_, ness2::herm_matrix_ness::Nft_, ness2::herm_matrix_ness::ret_, ness2::herm_matrix_ness::set_les, ness2::herm_matrix_ness::set_ret, ness2::fft_array::set_zero, ness2::herm_matrix_ness::size1_.
Referenced by green_equilibrium_ness.
void ness2::green_equilibrium_ness_fermi(herm_matrix_ness &G, DOS &dos, double beta, double mu, double h, fft_integral_method method, int limit, int nn)
References compute_lesser, FFT_ADAPTIVE, FFT_TRAPEZ, freq, ness2::grid_info::freq_at, green_equilibrium_ret_ness_adaptive, ness2::herm_matrix_ness::integral_transform_to_time, ness2::herm_matrix_ness::les_, ness2::herm_matrix_ness::Nft_, ness2::herm_matrix_ness::ret_, ness2::herm_matrix_ness::set_les, ness2::herm_matrix_ness::set_ret, ness2::fft_array::set_zero, ness2::herm_matrix_ness::size1_.
Referenced by green_equilibrium_ness.
void ness2::green_equilibrium_ret_ness_adaptive(herm_matrix_ness &G, DosFunction &dos, double h, int nn, int limit)
References fourier::adft_func::dft, ness2::herm_matrix_ness::Nft_, ness2::herm_matrix_ness::retarded, fourier::adft_func::sample, ness2::fft_array::set_element, ness2::fft_array::size1_, time.
Referenced by green_equilibrium_ness_bose, green_equilibrium_ness_fermi.
void ness2::ness2cntr(cntr::herm_matrix< T > &Gcntr, const herm_matrix_ness &Gness)
Convert a steady-state Green's function into a CNTR Green's function, assuming tranlstional invariance in time.
For each pair $ (t, t') $, if the relative time $ t - t' $ exists in the NESS domain, use $ G_{cntr}(t,t') = G_{ness}(t - t') $. Else, set to zero. GcntrType Any writable two-time Green's function (cntr::herm_matrix,cntr::herm_matrix_timestep, cntr::herm_matrix_moving, cntr::herm_matrix_timestep_moving) Gcntr Target two-time function Gness Source steady-state function
References ness2::herm_matrix_ness::get_les, ness2::herm_matrix_ness::get_ret, ness2::herm_matrix_ness::Nft_, cntr::herm_matrix< T >::nt, cntr::herm_matrix< T >::set_timestep_zero, cntr::herm_matrix< T >::size1, ness2::herm_matrix_ness::size1_, time.
Referenced by ness2cntr, ness2cntr.
void ness2::ness2cntr(cntr::herm_matrix_moving< T > &Gcntr, const herm_matrix_ness &Gness)
References ness2cntr, cntr::herm_matrix_moving< T >::tc.
void ness2::ness2cntr(cntr::herm_matrix_timestep< T > &Gcntr, const herm_matrix_ness &Gness)
References ness2::herm_matrix_ness::get_les, ness2::herm_matrix_ness::get_ret, ness2::herm_matrix_ness::Nft_, cntr::herm_matrix_timestep< T >::set_timestep_zero, cntr::herm_matrix_timestep< T >::size1, ness2::herm_matrix_ness::size1_, time, cntr::herm_matrix_timestep< T >::tstp.
void ness2::ness2cntr(cntr::herm_matrix_timestep_moving< T > &Gcntr, const herm_matrix_ness &Gness)
References ness2cntr.
void ness2::ness2cntr(cntr::herm_matrix_timestep_moving_view< T > &Gcntr, const herm_matrix_ness &Gness)
References ness2::herm_matrix_ness::get_les, ness2::herm_matrix_ness::get_ret, ness2::herm_matrix_ness::Nft_, cntr::herm_matrix_timestep_moving_view< T >::set_les, cntr::herm_matrix_timestep_moving_view< T >::set_ret, cntr::herm_matrix_timestep_moving_view< T >::set_timestep_zero, cntr::herm_matrix_timestep_moving_view< T >::size1, ness2::herm_matrix_ness::size1_, cntr::herm_matrix_timestep_moving_view< T >::tc, time.
const cplx ness2::NESS_II(0.0, 1.0)
herm_matrix_ness ness2::resample(double h_in, herm_matrix_ness &in, int factor)
Automatic upsampling of a herm_matrix_ness by a factor of '-factor' if a negative value is passed and an automatic downsampling ba a factor of 'factor' if a positive value is passed.
in Input steady-state Green's function (herm_matrix_ness). factor Coarse-graining factor if positive, if negative '-factor' is fine-graining factor.
void ness2::sigma_bath(double &ret, double &les, double omega, double h, dyson_bath_type bath_type, double bath_eta, double bath_beta, double bath_mu)
herm_matrix_ness ness2::upsample(double h_in, herm_matrix_ness &in, int factor)
Upsampling of a herm_matrix_ness to a finer time grid by transforming to frequency space, appending zeros until the new length $ N_{ft1} = N_{ft} \times factor $, and transforming back.
h_in Initial time step. in Input steady-state Green's function (herm_matrix_ness). factor Fine-graining factor, larger than one.